blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request or Idea
    url: https://github.com/NairoDorian/S2B2S/discussions
    about: Please post feature requests and ideas in our Discussions tab
  - name: 💬 General Discussion
    url: https://github.com/NairoDorian/S2B2S/discussions
    about: Ask questions and discuss ZER0 with the community
