/**
 * Runs repomix and merges its tree/structure output with per-file descriptions
 * from repomix-file-descriptions.md to produce a comprehensive architecture
 * overview (without file contents).
 *
 * Usage: bun run repomix:with-descriptions
 * Output: S2B2S_repomix_annotated.txt
 */

import { $ } from "bun";

const REPOMIX_OUTPUT = "S2B2S_repomix.txt";
const DESCRIPTIONS_FILE = "repomix-file-descriptions.md";
const MERGED_OUTPUT = "S2B2S_repomix_annotated.txt";

async function main() {
  console.log("🔍 Running repomix (architecture-only mode)...");
  const result = await $`bunx repomix`.nothrow();
  if (result.exitCode !== 0) {
    console.error("❌ Repomix failed:", result.stderr.toString());
    process.exit(1);
  }
  console.log(result.stderr.toString());

  // Read repomix output
  const repomixContent = await Bun.file(REPOMIX_OUTPUT).text();

  // Read descriptions
  let descriptionsContent = "";
  try {
    descriptionsContent = await Bun.file(DESCRIPTIONS_FILE).text();
  } catch {
    console.warn(
      "⚠️  No description file found, creating repomix-only output.",
    );
  }

  // Merge: repomix tree first, then descriptions
  const merged = [
    "<!-- Generated by repomix + repomix-with-descriptions.ts -->",
    "",
    repomixContent.trim(),
    "",
    "---",
    "",
    "## Per-File Descriptions",
    "",
    descriptionsContent.trim(),
    "",
    "---",
    `*Generated: ${new Date().toISOString()}*`,
  ].join("\n");

  await Bun.write(MERGED_OUTPUT, merged);
  console.log(`✅ Merged output written to ${MERGED_OUTPUT}`);
  console.log(`   Lines: ${merged.split("\n").length}`);
}

main().catch((err) => {
  console.error("❌ Fatal error:", err);
  process.exit(1);
});
