// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	changeBinding: (id: string, binding: string) => typedError<BindingResponse, string>(__TAURI_INVOKE("change_binding", { id, binding })),
	resetBinding: (id: string) => typedError<BindingResponse, string>(__TAURI_INVOKE("reset_binding", { id })),
	changePttSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_ptt_setting", { enabled })),
	changeAudioFeedbackSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_audio_feedback_setting", { enabled })),
	changeAudioFeedbackVolumeSetting: (volume: number | null) => typedError<null, string>(__TAURI_INVOKE("change_audio_feedback_volume_setting", { volume })),
	changeSoundThemeSetting: (theme: string) => typedError<null, string>(__TAURI_INVOKE("change_sound_theme_setting", { theme })),
	changeStartHiddenSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_start_hidden_setting", { enabled })),
	changeAutostartSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_autostart_setting", { enabled })),
	changeTranslateToEnglishSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_translate_to_english_setting", { enabled })),
	changeSelectedLanguageSetting: (language: string) => typedError<null, string>(__TAURI_INVOKE("change_selected_language_setting", { language })),
	changeOverlayPositionSetting: (position: string) => typedError<null, string>(__TAURI_INVOKE("change_overlay_position_setting", { position })),
	changeDebugModeSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_debug_mode_setting", { enabled })),
	changeWordCorrectionThresholdSetting: (threshold: number | null) => typedError<null, string>(__TAURI_INVOKE("change_word_correction_threshold_setting", { threshold })),
	changeExtraRecordingBufferSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_extra_recording_buffer_setting", { ms })),
	changePasteDelayMsSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_paste_delay_ms_setting", { ms })),
	changePasteMethodSetting: (method: string) => typedError<null, string>(__TAURI_INVOKE("change_paste_method_setting", { method })),
	getAvailableTypingTools: () => __TAURI_INVOKE<string[]>("get_available_typing_tools"),
	changeTypingToolSetting: (tool: string) => typedError<null, string>(__TAURI_INVOKE("change_typing_tool_setting", { tool })),
	changeExternalScriptPathSetting: (path: string | null) => typedError<null, string>(__TAURI_INVOKE("change_external_script_path_setting", { path })),
	changeClipboardHandlingSetting: (handling: string) => typedError<null, string>(__TAURI_INVOKE("change_clipboard_handling_setting", { handling })),
	changeAutoSubmitSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_auto_submit_setting", { enabled })),
	changeAutoSubmitKeySetting: (key: string) => typedError<null, string>(__TAURI_INVOKE("change_auto_submit_key_setting", { key })),
	changePostProcessEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_post_process_enabled_setting", { enabled })),
	changeExperimentalEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_experimental_enabled_setting", { enabled })),
	changePostProcessBaseUrlSetting: (providerId: string, baseUrl: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl })),
	changePostProcessApiKeySetting: (providerId: string, apiKey: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey })),
	changePostProcessModelSetting: (providerId: string, model: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_model_setting", { providerId, model })),
	setPostProcessProvider: (providerId: string) => typedError<null, string>(__TAURI_INVOKE("set_post_process_provider", { providerId })),
	fetchPostProcessModels: (providerId: string) => typedError<string[], string>(__TAURI_INVOKE("fetch_post_process_models", { providerId })),
	addPostProcessPrompt: (name: string, prompt: string) => typedError<LLMPrompt, string>(__TAURI_INVOKE("add_post_process_prompt", { name, prompt })),
	updatePostProcessPrompt: (id: string, name: string, prompt: string) => typedError<null, string>(__TAURI_INVOKE("update_post_process_prompt", { id, name, prompt })),
	deletePostProcessPrompt: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_post_process_prompt", { id })),
	setPostProcessSelectedPrompt: (id: string) => typedError<null, string>(__TAURI_INVOKE("set_post_process_selected_prompt", { id })),
	addLlmModel: (providerId: string, model: string, label: string) => typedError<LLMModel, string>(__TAURI_INVOKE("add_llm_model", { providerId, model, label })),
	deleteLlmModel: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_llm_model", { id })),
	addPostProcessAction: (name: string, prompt: string, llmModelId: string | null, icon: string, triggerKey: number | null) => typedError<PostProcessAction, string>(__TAURI_INVOKE("add_post_process_action", { name, prompt, llmModelId, icon, triggerKey })),
	updatePostProcessAction: (id: string, name: string, prompt: string, llmModelId: string | null, icon: string, triggerKey: number | null) => typedError<null, string>(__TAURI_INVOKE("update_post_process_action", { id, name, prompt, llmModelId, icon, triggerKey })),
	deletePostProcessAction: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_post_process_action", { id })),
	updateCustomWords: (words: string[]) => typedError<null, string>(__TAURI_INVOKE("update_custom_words", { words })),
	/**
	 *  Temporarily unregister a binding while the user is editing it in the UI.
	 *  This avoids firing the action while keys are being recorded.
	 */
	suspendBinding: (id: string) => typedError<null, string>(__TAURI_INVOKE("suspend_binding", { id })),
	/**  Re-register the binding after the user has finished editing. */
	resumeBinding: (id: string) => typedError<null, string>(__TAURI_INVOKE("resume_binding", { id })),
	changeMuteWhileRecordingSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_mute_while_recording_setting", { enabled })),
	changeAppendTrailingSpaceSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_append_trailing_space_setting", { enabled })),
	changeLazyStreamCloseSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_lazy_stream_close_setting", { enabled })),
	changeAppLanguageSetting: (language: string) => typedError<null, string>(__TAURI_INVOKE("change_app_language_setting", { language })),
	changeUpdateChecksSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_update_checks_setting", { enabled })),
	/**
	 *  Change the keyboard implementation with runtime switching.
	 *  This will unregister all shortcuts from the old implementation,
	 *  validate shortcuts for the new implementation (resetting invalid ones to defaults),
	 *  and register them with the new implementation.
	 */
	changeKeyboardImplementationSetting: (implementation: string) => typedError<ImplementationChangeResult, string>(__TAURI_INVOKE("change_keyboard_implementation_setting", { implementation })),
	/**  Get the current keyboard implementation */
	getKeyboardImplementation: () => __TAURI_INVOKE<string>("get_keyboard_implementation"),
	changeShowTrayIconSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_show_tray_icon_setting", { enabled })),
	changeWhisperAcceleratorSetting: (accelerator: WhisperAcceleratorSetting) => typedError<null, string>(__TAURI_INVOKE("change_whisper_accelerator_setting", { accelerator })),
	changeOrtAcceleratorSetting: (accelerator: OrtAcceleratorSetting) => typedError<null, string>(__TAURI_INVOKE("change_ort_accelerator_setting", { accelerator })),
	changeParakeetStreamingSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_parakeet_streaming_setting", { enabled })),
	changeWhisperGpuDevice: (device: number) => typedError<null, string>(__TAURI_INVOKE("change_whisper_gpu_device", { device })),
	/**
	 *  Return which accelerators and GPU devices are available for this build.
	 * 
	 *  First-call cost is dominated by enumerating GPU devices through the
	 *  whisper.cpp Metal/Vulkan backend, which loads dynamic libraries and
	 *  probes hardware. Run it on the blocking pool so the webview thread
	 *  stays responsive — see also the startup pre-warm in `lib.rs`.
	 */
	getAvailableAccelerators: () => __TAURI_INVOKE<AvailableAccelerators>("get_available_accelerators"),
	changeTextReplacementDecapitalizeAfterEditKeyEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_text_replacement_decapitalize_after_edit_key_enabled_setting", { enabled })),
	changeTextReplacementDecapitalizeAfterEditKeySetting: (key: string) => typedError<null, string>(__TAURI_INVOKE("change_text_replacement_decapitalize_after_edit_key_setting", { key })),
	changeTextReplacementDecapitalizeAfterEditSecondaryKeyEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_text_replacement_decapitalize_after_edit_secondary_key_enabled_setting", { enabled })),
	changeTextReplacementDecapitalizeAfterEditSecondaryKeySetting: (key: string) => typedError<null, string>(__TAURI_INVOKE("change_text_replacement_decapitalize_after_edit_secondary_key_setting", { key })),
	changeTextReplacementDecapitalizeTimeoutMsSetting: (timeoutMs: number) => typedError<null, string>(__TAURI_INVOKE("change_text_replacement_decapitalize_timeout_ms_setting", { timeoutMs })),
	changeTextReplacementDecapitalizeStandardPostRecordingMonitorMsSetting: (timeoutMs: number) => typedError<null, string>(__TAURI_INVOKE("change_text_replacement_decapitalize_standard_post_recording_monitor_ms_setting", { timeoutMs })),
	getTextReplacementDecapitalizeOverlayState: () => __TAURI_INVOKE<DecapitalizeOverlayStateResponse>("get_text_replacement_decapitalize_overlay_state"),
	/**  Start key recording mode */
	startKeyListenerRecording: (bindingId: string) => typedError<null, string>(__TAURI_INVOKE("start_key_listener_recording", { bindingId })),
	/**  Stop key recording mode */
	stopKeyListenerRecording: () => typedError<null, string>(__TAURI_INVOKE("stop_key_listener_recording")),
	triggerUpdateCheck: () => typedError<null, string>(__TAURI_INVOKE("trigger_update_check")),
	showMainWindowCommand: () => typedError<null, string>(__TAURI_INVOKE("show_main_window_command")),
	cancelOperation: () => __TAURI_INVOKE<void>("cancel_operation"),
	isPortable: () => __TAURI_INVOKE<boolean>("is_portable"),
	getAppDirPath: () => typedError<string, string>(__TAURI_INVOKE("get_app_dir_path")),
	exportSettings: (path: string) => typedError<null, string>(__TAURI_INVOKE("export_settings", { path })),
	importSettings: (path: string) => typedError<null, string>(__TAURI_INVOKE("import_settings", { path })),
	getAppSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_app_settings")),
	getDefaultSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_default_settings")),
	getLogDirPath: () => typedError<string, string>(__TAURI_INVOKE("get_log_dir_path")),
	setLogLevel: (level: LogLevel) => typedError<null, string>(__TAURI_INVOKE("set_log_level", { level })),
	getRecentLogs: (maxLines: number) => typedError<string, string>(__TAURI_INVOKE("get_recent_logs", { maxLines })),
	clearLogs: () => typedError<null, string>(__TAURI_INVOKE("clear_logs")),
	openRecordingsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_recordings_folder")),
	openLogDir: () => typedError<null, string>(__TAURI_INVOKE("open_log_dir")),
	openAppDataDir: () => typedError<null, string>(__TAURI_INVOKE("open_app_data_dir")),
	/**
	 *  Check if Apple Intelligence is available on this device.
	 *  Called by the frontend when the user selects Apple Intelligence provider.
	 */
	checkAppleIntelligenceAvailable: () => __TAURI_INVOKE<boolean>("check_apple_intelligence_available"),
	/**
	 *  Try to initialize Enigo (keyboard/mouse simulation).
	 *  On macOS, this will return an error if accessibility permissions are not granted.
	 */
	initializeEnigo: () => typedError<null, string>(__TAURI_INVOKE("initialize_enigo")),
	/**
	 *  Initialize keyboard shortcuts.
	 *  On macOS, this should be called after accessibility permissions are granted.
	 *  This is idempotent - calling it multiple times is safe.
	 */
	initializeShortcuts: () => typedError<null, string>(__TAURI_INVOKE("initialize_shortcuts")),
	getAvailableModels: () => typedError<ModelInfo[], string>(__TAURI_INVOKE("get_available_models")),
	getModelInfo: (modelId: string) => typedError<{
	id: string,
	name: string,
	description: string,
	filename: string,
	url: string | null,
	sha256: string | null,
	size_mb: number | null,
	is_downloaded: boolean,
	is_downloading: boolean,
	partial_size: number | null,
	is_directory: boolean,
	engine_type: EngineType,
	accuracy_score: number | null,
	speed_score: number | null,
	supports_translation: boolean,
	is_recommended: boolean,
	supported_languages: string[],
	supports_language_selection: boolean,
	is_custom: boolean,
} | null, string>(__TAURI_INVOKE("get_model_info", { modelId })),
	downloadModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("download_model", { modelId })),
	deleteModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("delete_model", { modelId })),
	cancelDownload: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_download", { modelId })),
	setActiveModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("set_active_model", { modelId })),
	getCurrentModel: () => typedError<string, string>(__TAURI_INVOKE("get_current_model")),
	getTranscriptionModelStatus: () => typedError<string | null, string>(__TAURI_INVOKE("get_transcription_model_status")),
	isModelLoading: () => typedError<boolean, string>(__TAURI_INVOKE("is_model_loading")),
	hasAnyModelsAvailable: () => typedError<boolean, string>(__TAURI_INVOKE("has_any_models_available")),
	hasAnyModelsOrDownloads: () => typedError<boolean, string>(__TAURI_INVOKE("has_any_models_or_downloads")),
	getActiveGpuVramStatus: () => typedError<GpuVramStatus, string>(__TAURI_INVOKE("get_active_gpu_vram_status")),
	updateMicrophoneMode: (alwaysOn: boolean) => typedError<null, string>(__TAURI_INVOKE("update_microphone_mode", { alwaysOn })),
	getMicrophoneMode: () => typedError<boolean, string>(__TAURI_INVOKE("get_microphone_mode")),
	getWindowsMicrophonePermissionStatus: () => __TAURI_INVOKE<WindowsMicrophonePermissionStatus>("get_windows_microphone_permission_status"),
	openMicrophonePrivacySettings: () => typedError<null, string>(__TAURI_INVOKE("open_microphone_privacy_settings")),
	getAvailableMicrophones: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("get_available_microphones")),
	setSelectedMicrophone: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_selected_microphone", { deviceName })),
	getSelectedMicrophone: () => typedError<string, string>(__TAURI_INVOKE("get_selected_microphone")),
	getAvailableOutputDevices: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("get_available_output_devices")),
	setSelectedOutputDevice: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_selected_output_device", { deviceName })),
	getSelectedOutputDevice: () => typedError<string, string>(__TAURI_INVOKE("get_selected_output_device")),
	playTestSound: (soundType: string) => __TAURI_INVOKE<void>("play_test_sound", { soundType }),
	checkCustomSounds: () => __TAURI_INVOKE<CustomSounds>("check_custom_sounds"),
	setClamshellMicrophone: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_clamshell_microphone", { deviceName })),
	getClamshellMicrophone: () => typedError<string, string>(__TAURI_INVOKE("get_clamshell_microphone")),
	isRecording: () => __TAURI_INVOKE<boolean>("is_recording"),
	toggleRecordingPause: () => __TAURI_INVOKE<boolean>("toggle_recording_pause"),
	isRecordingPaused: () => __TAURI_INVOKE<boolean>("is_recording_paused"),
	setNoiseSuppressionEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_noise_suppression_enabled", { enabled })),
	setVadMode: (mode: string) => typedError<null, string>(__TAURI_INVOKE("set_vad_mode", { mode })),
	startContinuousVoiceMode: () => typedError<null, string>(__TAURI_INVOKE("start_continuous_voice_mode")),
	stopContinuousVoiceMode: () => typedError<null, string>(__TAURI_INVOKE("stop_continuous_voice_mode")),
	setRecordingAutoStop: (enabled: boolean, silenceSecs: number) => typedError<null, string>(__TAURI_INVOKE("set_recording_auto_stop", { enabled, silenceSecs })),
	setModelUnloadTimeout: (timeout: ModelUnloadTimeout) => __TAURI_INVOKE<void>("set_model_unload_timeout", { timeout }),
	getModelLoadStatus: () => typedError<ModelLoadStatus, string>(__TAURI_INVOKE("get_model_load_status")),
	unloadModelManually: () => typedError<null, string>(__TAURI_INVOKE("unload_model_manually")),
	setLongAudioModel: (model: string | null) => __TAURI_INVOKE<void>("set_long_audio_model", { model }),
	setLongAudioThreshold: (threshold: number | null) => __TAURI_INVOKE<void>("set_long_audio_threshold", { threshold }),
	getHistoryEntries: (cursor: number | null, limit: number | null) => typedError<PaginatedHistory, string>(__TAURI_INVOKE("get_history_entries", { cursor, limit })),
	toggleHistoryEntrySaved: (id: number) => typedError<null, string>(__TAURI_INVOKE("toggle_history_entry_saved", { id })),
	getAudioFilePath: (fileName: string) => typedError<string, string>(__TAURI_INVOKE("get_audio_file_path", { fileName })),
	deleteAllHistoryEntries: () => typedError<number, string>(__TAURI_INVOKE("delete_all_history_entries")),
	deleteHistoryEntry: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_history_entry", { id })),
	retryHistoryEntryTranscription: (id: number) => typedError<null, string>(__TAURI_INVOKE("retry_history_entry_transcription", { id })),
	/**
	 *  Re-run a post-process action over an existing history entry and persist
	 *  the processed text. Returns the updated entry.
	 */
	applyActionToHistoryEntry: (id: number, actionId: string) => typedError<HistoryEntry, string>(__TAURI_INVOKE("apply_action_to_history_entry", { id, actionId })),
	updateHistoryLimit: (limit: number) => typedError<null, string>(__TAURI_INVOKE("update_history_limit", { limit })),
	updateRecordingRetentionPeriod: (period: string) => typedError<null, string>(__TAURI_INVOKE("update_recording_retention_period", { period })),
	deleteHistoryEntries: (ids: number[]) => typedError<null, string>(__TAURI_INVOKE("delete_history_entries", { ids })),
	exportHistoryEntries: (ids: number[], filePath: string) => typedError<null, string>(__TAURI_INVOKE("export_history_entries", { ids, filePath })),
	regenerateHistoryEntry: (id: number) => typedError<null, string>(__TAURI_INVOKE("regenerate_history_entry", { id })),
	/**  Speak arbitrary text aloud (sanitize → paginate → streaming synthesis). */
	ttsSpeak: (text: string) => typedError<null, string>(__TAURI_INVOKE("tts_speak", { text })),
	/**  Speak the current clipboard text. */
	ttsSpeakClipboard: () => typedError<null, string>(__TAURI_INVOKE("tts_speak_clipboard")),
	ttsStop: () => typedError<null, string>(__TAURI_INVOKE("tts_stop")),
	ttsPause: () => typedError<null, string>(__TAURI_INVOKE("tts_pause")),
	ttsResume: () => typedError<null, string>(__TAURI_INVOKE("tts_resume")),
	ttsIsPlaying: () => typedError<boolean, string>(__TAURI_INVOKE("tts_is_playing")),
	/**  Enumerate available voices for a specific engine, or defaults to the configured engine. */
	ttsGetVoices: (engine: "piper" | "kokoro" | "kitten" | "pocket" | "sapi" | "openai" | "elevenlabs" | "cartesia" | null) => typedError<Voice[], string>(__TAURI_INVOKE("tts_get_voices", { engine })),
	/**  Unload the warm TTS model/server (tray "Unload model" parity). */
	ttsUnloadEngine: () => typedError<boolean, string>(__TAURI_INVOKE("tts_unload_engine")),
	getPiperServerStatus: () => typedError<PiperServerStatus, string>(__TAURI_INVOKE("get_piper_server_status")),
	getLocalTtsStatus: (engine: string) => typedError<string | null, string>(__TAURI_INVOKE("get_local_tts_status", { engine })),
	pocketImportClonedVoice: (sourcePath: string) => typedError<Voice, string>(__TAURI_INVOKE("pocket_import_cloned_voice", { sourcePath })),
	/**  Replace the whole TTS configuration (engine, voice, speed, volume, toggles). */
	changeTtsConfig: (config: TtsConfig) => typedError<null, string>(__TAURI_INVOKE("change_tts_config", { config })),
	/**  Play the startup greeting audio using customized greeting settings. */
	ttsPlayGreeting: () => typedError<null, string>(__TAURI_INVOKE("tts_play_greeting")),
	/**  Save the most recent TTS audio to a user-chosen file path. */
	ttsSaveToFile: (targetPath: string) => typedError<null, string>(__TAURI_INVOKE("tts_save_to_file", { targetPath })),
	/**  Ask the Brain; streams `brain:token` / `brain:sentence` events and returns the full reply. */
	brainAsk: (text: string) => typedError<string, string>(__TAURI_INVOKE("brain_ask", { text })),
	/**
	 *  AI Replace: speak an instruction to rewrite selected text via the Brain.
	 *  Returns the rewritten text; caller pastes it at the cursor.
	 */
	aiReplaceSelection: (instruction: string, selectedText: string) => typedError<string, string>(__TAURI_INVOKE("ai_replace_selection", { instruction, selectedText })),
	/**  Abort the in-flight Brain stream and stop any speech it queued (barge-in). */
	brainAbort: () => typedError<null, string>(__TAURI_INVOKE("brain_abort")),
	brainClearHistory: () => typedError<null, string>(__TAURI_INVOKE("brain_clear_history")),
	/**  List models available at the configured Brain endpoint (Ollama, LM Studio, cloud…). */
	fetchBrainModels: () => typedError<string[], string>(__TAURI_INVOKE("fetch_brain_models")),
	/**  Replace the whole Brain configuration (endpoint, model, prompt, toggles). */
	changeBrainConfig: (config: BrainConfig) => typedError<null, string>(__TAURI_INVOKE("change_brain_config", { config })),
	setBrainProvider: (providerId: string) => typedError<null, string>(__TAURI_INVOKE("set_brain_provider", { providerId })),
	changeBrainBaseUrlSetting: (providerId: string, baseUrl: string) => typedError<null, string>(__TAURI_INVOKE("change_brain_base_url_setting", { providerId, baseUrl })),
	changeBrainApiKeySetting: (providerId: string, apiKey: string) => typedError<null, string>(__TAURI_INVOKE("change_brain_api_key_setting", { providerId, apiKey })),
	changeBrainModelSetting: (providerId: string, model: string) => typedError<null, string>(__TAURI_INVOKE("change_brain_model_setting", { providerId, model })),
	downloadLlamaModels: () => typedError<null, string>(__TAURI_INVOKE("download_llama_models")),
	getLlamaModelsStatus: () => typedError<boolean, string>(__TAURI_INVOKE("get_llama_models_status")),
	isLlamaDownloading: () => typedError<boolean, string>(__TAURI_INVOKE("is_llama_downloading")),
	fetchLlamaReleases: () => typedError<LlamaRelease[], string>(__TAURI_INVOKE("fetch_llama_releases")),
	downloadLlamaServer: (backend: string, releaseTag: string, downloadUrl: string) => typedError<null, string>(__TAURI_INVOKE("download_llama_server", { backend, releaseTag, downloadUrl })),
	getDownloadedLlamaServers: () => typedError<DownloadedServer[], string>(__TAURI_INVOKE("get_downloaded_llama_servers")),
	removeLlamaServer: (backend: string, releaseTag: string) => typedError<null, string>(__TAURI_INVOKE("remove_llama_server", { backend, releaseTag })),
	setLlamaServerActive: (backend: string, releaseTag: string) => typedError<null, string>(__TAURI_INVOKE("set_llama_server_active", { backend, releaseTag })),
	getLlamaServerConfig: () => typedError<LlamaServerConfig, string>(__TAURI_INVOKE("get_llama_server_config")),
	detectGpuType: () => typedError<string, string>(__TAURI_INVOKE("detect_gpu_type")),
	discoverLocalBrains: () => typedError<DiscoveredServer[], string>(__TAURI_INVOKE("discover_local_brains")),
	isOllamaRunning: () => __TAURI_INVOKE<boolean>("is_ollama_running"),
	wakeWordStart: () => typedError<null, string>(__TAURI_INVOKE("wake_word_start")),
	wakeWordStop: () => typedError<null, string>(__TAURI_INVOKE("wake_word_stop")),
	wakeWordSetConfig: (config: WakeWordConfig) => typedError<null, string>(__TAURI_INVOKE("wake_word_set_config", { config })),
	wakeWordStatus: () => typedError<boolean, string>(__TAURI_INVOKE("wake_word_status")),
	/**
	 *  Stub implementation for non-macOS platforms
	 *  Always returns false since laptop detection is macOS-specific
	 */
	isLaptop: () => typedError<boolean, string>(__TAURI_INVOKE("is_laptop")),
	getSystemRam: () => typedError<SystemRamInfo, string>(__TAURI_INVOKE("get_system_ram")),
	checkSpeechRuntimeInstalled: () => __TAURI_INVOKE<boolean>("check_speech_runtime_installed"),
	installSpeechRuntime: () => typedError<null, string>(__TAURI_INVOKE("install_speech_runtime")),
	/**  Probe the current machine's overlay capabilities (WebGPU, Vulkan, cursor position, etc.). */
	overlayFxProbeCapabilities: () => __TAURI_INVOKE<OverlayCapabilities>("overlay_fx_probe_capabilities"),
	/**  Show the brain overlay at the cursor position and begin conversation. */
	overlayFxShowConversation: () => typedError<null, string>(__TAURI_INVOKE("overlay_fx_show_conversation")),
	/**  Hide the brain overlay and end the conversation. */
	overlayFxDismiss: () => typedError<null, string>(__TAURI_INVOKE("overlay_fx_dismiss")),
};

/** Events */
export const events = {
	historyUpdatePayload: makeEvent<HistoryUpdatePayload>("history-update-payload"),
};

/* Types */
export type AppSettings = {
	bindings: { [key in string]: ShortcutBinding },
	push_to_talk: boolean,
	audio_feedback: boolean,
	audio_feedback_volume?: number | null,
	sound_theme?: SoundTheme,
	start_hidden?: boolean,
	autostart_enabled?: boolean,
	update_checks_enabled?: boolean,
	selected_model?: string,
	always_on_microphone?: boolean,
	selected_microphone?: string | null,
	clamshell_microphone?: string | null,
	selected_output_device?: string | null,
	translate_to_english?: boolean,
	selected_language?: string,
	overlay_position?: OverlayPosition,
	/**  Overlay window behaviour + visual customization. */
	overlay_window?: OverlayWindowConfig,
	/**  Native wgpu cursor trail + click ripple effects. */
	wgpu_trail?: WgpuTrailConfig,
	debug_mode?: boolean,
	log_level?: LogLevel,
	custom_words?: string[],
	model_unload_timeout?: ModelUnloadTimeout,
	word_correction_threshold?: number | null,
	history_limit?: number,
	recording_retention_period?: RecordingRetentionPeriod,
	paste_method?: PasteMethod,
	clipboard_handling?: ClipboardHandling,
	auto_submit?: boolean,
	auto_submit_key?: AutoSubmitKey,
	post_process_enabled?: boolean,
	post_process_provider_id?: string,
	post_process_providers?: PostProcessProvider[],
	post_process_api_keys?: SecretMap,
	post_process_models?: { [key in string]: string },
	post_process_prompts?: LLMPrompt[],
	post_process_selected_prompt_id?: string | null,
	llm_models?: LLMModel[],
	post_process_actions?: PostProcessAction[],
	post_process_actions_initialized?: boolean,
	mute_while_recording?: boolean,
	append_trailing_space?: boolean,
	app_language?: string,
	experimental_enabled?: boolean,
	lazy_stream_close?: boolean,
	keyboard_implementation?: KeyboardImplementation,
	show_tray_icon?: boolean,
	paste_delay_ms?: number,
	typing_tool?: TypingTool,
	external_script_path: string | null,
	custom_filler_words?: string[] | null,
	whisper_accelerator?: WhisperAcceleratorSetting,
	ort_accelerator?: OrtAcceleratorSetting,
	whisper_gpu_device?: number,
	extra_recording_buffer_ms?: number,
	/**  Text-to-speech ("Read Anywhere" / CopySpeak) settings. */
	tts?: TtsConfig,
	/**  Streaming LLM "Brain" subsystem settings (separate from post-processing). */
	brain?: BrainConfig,
	long_audio_model?: string | null,
	long_audio_threshold_seconds?: number | null,
	noise_suppression_enabled?: boolean,
	vad_mode?: string,
	rnnoise_voice_threshold?: number | null,
	llama_server?: LlamaServerConfig,
	/**  Multi-STT: run multiple transcription models in parallel and merge results. */
	multi_stt_enabled?: boolean,
	multi_stt_models?: string[],
	/**  Multi-STT post-processing prompt. {transcriptions} is replaced with the model results. */
	multi_stt_prompt?: string,
	/**
	 *  Parakeet streaming toggle: when enabled, all UnifiedParakeet models
	 *  (Unified 0.6B + EOU 120M) use the streaming API for progressive partial
	 *  results with stateful RNNT decoder. When disabled, uses offline /transcribe.
	 */
	parakeet_streaming_enabled?: boolean,
	control_server_token?: string | null,
	recording_auto_stop_enabled?: boolean,
	recording_auto_stop_timeout_seconds?: number,
	recording_auto_stop_paste?: boolean,
	text_replacement_decapitalize_after_edit_key_enabled?: boolean,
	text_replacement_decapitalize_after_edit_key?: string,
	text_replacement_decapitalize_after_edit_secondary_key_enabled?: boolean,
	text_replacement_decapitalize_after_edit_secondary_key?: string,
	text_replacement_decapitalize_timeout_ms?: number,
	text_replacement_decapitalize_standard_post_recording_monitor_ms?: number,
};

export type AudioDevice = {
	index: string,
	name: string,
	is_default: boolean,
};

export type AudioFormat = "wav" | "mp3" | "ogg" | "flac";

export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter";

export type AvailableAccelerators = {
	whisper: string[],
	ort: string[],
	gpu_devices: GpuDeviceOption[],
};

export type BindingResponse = {
	success: boolean,
	binding: ShortcutBinding | null,
	error: string | null,
};

/**  The "Brain": a streaming LLM subsystem, independent of dictation post-processing. */
export type BrainConfig = {
	enabled: boolean,
	provider_id: string,
	providers: PostProcessProvider[],
	api_keys: SecretMap,
	models: { [key in string]: string },
	system_prompt: string,
	/**  How many prior turns to keep in the context window (0 = stateless). */
	context_turns: number,
	/**  Speak the Brain's reply aloud via the TTS subsystem. */
	read_aloud: boolean,
	/**
	 *  Separate system prompt appended when read-aloud is ON.
	 *  Instructs the model to answer conversationally for listening.
	 */
	speakable_output_prompt?: string,
	/**  Dummy prompt sent to warm up the Brain model when it loads into VRAM. */
	warmup_prompt?: string,
	/**  Conversation mode: push_to_talk | toggle | hands_free */
	conversation_mode?: string,
	/**  Endpoint silence preset: snappy(300ms) | balanced(600ms) | patient(1200ms) */
	endpoint_preset?: string,
	/**  Headphone mode — enables barge-in during TTS playback */
	headphone_mode?: boolean,
	/**  Auto-rearm mic after reply in hands-free mode */
	auto_listen?: boolean,
	/**
	 *  Send the WAV audio recording as `input_audio` to the multimodal Brain model
	 *  (Gemma 4 supports native audio transcription as an extra STT pass).
	 */
	multimodal_audio_enabled?: boolean,
	/**
	 *  Send a screenshot/image as `image_url` to the multimodal Brain model.
	 *  When enabled, images can be passed alongside text prompts for vision understanding.
	 */
	multimodal_image_enabled?: boolean,
	/**
	 *  Bypass STT models and send raw audio directly to the multimodal Brain
	 *  with a fixed transcription prompt. Gemma 4 handles both transcription
	 *  and response using its native audio understanding.
	 */
	brain_only_transcription?: boolean,
};

export type CartesiaConfig = {
	api_key: string,
	model_id: string,
	voice_id: string,
	voice_name: string | null,
	output_format: string,
	use_manual_voice_id: boolean,
};

export type ClipboardHandling = "dont_modify" | "copy_to_clipboard";

export type CustomSounds = {
	start: boolean,
	stop: boolean,
};

export type DecapitalizeOverlayStateResponse = {
	decapitalize_eligible: boolean,
	decapitalize_armed: boolean,
};

export type DiscoveredServer = {
	name: string,
	base_url: string,
	models: string[],
	provider_id: string,
};

export type DownloadedServer = {
	backend: string,
	release_tag: string,
	path: string,
	size_bytes: number,
};

export type ElevenLabsConfig = {
	api_key: string,
	voice_id: string,
	voice_name: string | null,
	model_id: string,
	output_format: ElevenLabsOutputFormat,
	voice_stability?: number | null,
	voice_similarity_boost?: number | null,
	voice_style: number | null,
	use_speaker_boost: boolean | null,
	use_manual_voice_id: boolean,
};

export type ElevenLabsOutputFormat = "mp3_44100_128" | "mp3_44100_192" | "mp3_44100_32" | "mp3_22050_32" | "pcm_44100" | "pcm_22050" | "pcm_16000" | "ogg_vorbis_44100" | "ogg_vorbis_22050" | "flac_44100" | "mulaw_8000";

export type EngineType = "Whisper" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere" | "UnifiedParakeet";

export type GpuDeviceOption = {
	id: number,
	name: string,
	total_vram_mb: number,
};

export type GpuVramStatus = {
	is_supported: boolean,
	adapter_name: string | null,
	/**  Total dedicated VRAM on the GPU in MB */
	total_vram_mb: number,
	/**  System-wide VRAM currently in use (matches Task Manager) */
	used_vram_mb: number,
	/**  System-wide free VRAM */
	free_vram_mb: number,
	/**  This process's VRAM budget usage (from DXGI) */
	process_used_mb: number,
	/**  This process's VRAM budget */
	process_budget_mb: number,
	/**  Detected LLM server processes consuming VRAM */
	llm_servers: LlmServerInfo[],
	/**  Unix ms timestamp of when this snapshot was taken */
	updated_at_unix_ms: number | null,
	error: string | null,
};

export type HistoryEntry = {
	id: number,
	file_name: string,
	timestamp: number,
	saved: boolean,
	title: string,
	transcription_text: string,
	post_processed_text: string | null,
	post_process_prompt: string | null,
	post_process_requested: boolean,
	entry_type: string,
	model_name: string | null,
	model_info: string | null,
	duration_ms: number | null,
};

export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number };

/**  Result of changing keyboard implementation */
export type ImplementationChangeResult = {
	success: boolean,
	/**  List of binding IDs that were reset to defaults due to incompatibility */
	reset_bindings: string[],
};

export type KeyboardImplementation = "tauri" | "key_listener";

/**
 *  A saved language model: a (provider, model) pair the user added in the
 *  Models > Language Models tab. Referenced by post-process actions.
 */
export type LLMModel = {
	id: string,
	provider_id: string,
	model: string,
	label: string,
};

export type LLMPrompt = {
	id: string,
	name: string,
	prompt: string,
};

export type LlamaAsset = {
	name: string,
	backend: string,
	os: string,
	arch: string,
	download_url: string,
	size_bytes: number,
};

export type LlamaRelease = {
	tag: string,
	name: string,
	assets: LlamaAsset[],
};

export type LlamaServerConfig = {
	backend: string,
	release_tag: string,
};

export type LlmServerInfo = {
	name: string,
	pid: number,
};

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

export type ModelInfo = {
	id: string,
	name: string,
	description: string,
	filename: string,
	url: string | null,
	sha256: string | null,
	size_mb: number | null,
	is_downloaded: boolean,
	is_downloading: boolean,
	partial_size: number | null,
	is_directory: boolean,
	engine_type: EngineType,
	accuracy_score: number | null,
	speed_score: number | null,
	supports_translation: boolean,
	is_recommended: boolean,
	supported_languages: string[],
	supports_language_selection: boolean,
	is_custom: boolean,
};

export type ModelLoadStatus = {
	is_loaded: boolean,
	current_model: string | null,
};

export type ModelUnloadTimeout = "never" | "immediately" | "min2" | "min5" | "min10" | "min15" | "hour1" | "sec15";

export type OpenAIConfig = {
	api_key: string,
	model: string,
	voice: string,
};

export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm";

/**  Overlay capability probe result — returned to the frontend, typed via specta. */
export type OverlayCapabilities = {
	os: string,
	webgpu: boolean,
	vulkan: boolean,
	cursor_position: boolean,
	layer_shell: boolean,
	native_transparent: boolean,
};

/**
 *  Overlay approach: Tauri-only (CopySpeak HUD style — alwaysOnTop + transparent)
 *  or OS-native (NSPanel/Win32 HWND_TOPMOST/GTK layer-shell — Handy style).
 */
export type OverlayMode = 
/**  Tauri `always_on_top(true)` + `transparent(true)` only — simpler, fewer deps. */
"tauri" | 
/**  Per-OS native window APIs (NSPanel, Win32 topmost, GTK layer-shell). */
"os_native";

export type OverlayPosition = "none" | "top" | "bottom";

/**  Configuration for the recording overlay window (the pill shown during dictation/TTS). */
export type OverlayWindowConfig = {
	/**  Which overlay approach to use. */
	mode?: OverlayMode,
	/**  Position on screen. */
	position?: OverlayPosition,
	/**  Overlay width in logical pixels. */
	width?: number,
	/**  Overlay height in logical pixels. */
	height?: number,
	/**  Overlay background opacity (0.0–1.0). */
	opacity?: number | null,
	/**  Round the corners with this radius (0 = square). */
	corner_radius?: number | null,
	/**  Show a text reply bubble next to the cursor during Brain conversation. */
	reply_bubble?: boolean,
	/**  Fade-out time in milliseconds. */
	fade_ms?: number,
};

export type PaginatedHistory = {
	entries: HistoryEntry[],
	has_more: boolean,
};

/**  Pagination config: split long text into sentence-bounded fragments before synthesis. */
export type PaginationConfig = {
	enabled: boolean,
	/**  Target maximum characters per fragment. */
	fragment_size: number,
};

export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script";

export type PermissionAccess = "allowed" | "denied" | "unknown";

/**  Piper (persistent local HTTP server) configuration. */
export type PiperConfig = {
	/**  Path to the python executable that hosts `piper.http_server`. */
	python_path: string,
	/**  Directory containing Piper `.onnx` voices (defaults to ~/piper-voices when empty). */
	data_dir: string,
	/**  Use the CUDA execution provider when starting the server. */
	cuda: boolean,
};

export type PiperServerStatus = {
	running: boolean,
	model: string | null,
	port: number | null,
	cuda: boolean,
	ready: boolean,
};

/**
 *  A post-processing action: a prompt applied to the transcription through a
 *  saved language model. Can be triggered by a dedicated global shortcut
 *  (stored in `bindings` under `ppa_<id>`) or by pressing `trigger_key`
 *  while a recording is in progress.
 */
export type PostProcessAction = {
	id: string,
	name: string,
	prompt: string,
	llm_model_id?: string | null,
	icon?: string,
	trigger_key?: number | null,
};

export type PostProcessProvider = {
	id: string,
	label: string,
	base_url: string,
	allow_base_url_edit?: boolean,
	allow_insecure_http?: boolean,
	models_endpoint?: string | null,
	supports_structured_output?: boolean,
};

export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days3" | "weeks2" | "months3";

/**  Pre-TTS text sanitization toggles (markdown stripping + speech normalization). */
export type SanitizationConfig = {
	enabled: boolean,
	/**  Strip markdown syntax (code blocks, links, headers, lists, quotes). */
	markdown: boolean,
	/**  Expand abbreviations/symbols/units for speech (e.g. "$50" -> "50 dollars"). */
	tts_normalization: boolean,
};

export type SecretMap = { [key in string]: string };

export type ShortcutBinding = {
	id: string,
	name: string,
	description: string,
	default_binding: string,
	current_binding: string,
};

export type SoundTheme = "marimba" | "pop" | "custom";

export type SystemRamInfo = {
	total_mb: number,
	used_mb: number,
	free_mb: number,
};

/**  Text-to-speech ("Read Anywhere" / CopySpeak) configuration. */
export type TtsConfig = {
	enabled: boolean,
	engine: TtsEngine,
	/**  Engine-specific voice id (e.g. a Piper voice filename without extension). */
	voice: string,
	/**  Playback rate; one owner — passed to the engine, never applied twice (CopySpeak C1). */
	speed: number | null,
	/**  Playback volume 0-100. */
	volume: number,
	pagination: PaginationConfig,
	sanitization?: SanitizationConfig,
	piper: PiperConfig,
	/**
	 *  CopySpeak double-copy trigger: copy the same text twice within the
	 *  window to speak it automatically (currently Windows-only detection).
	 */
	double_copy_enabled?: boolean,
	double_copy_window_ms?: number,
	play_startup_greeting?: boolean,
	greeting?: TtsGreetingConfig,
	openai?: OpenAIConfig,
	elevenlabs?: ElevenLabsConfig,
	cartesia?: CartesiaConfig,
	/**  Number of parallel Kokoro synthesis workers (auto-tuned from CPU count, min 1, max 8). */
	tts_workers?: number,
	/**  Shorten the first chunk to reduce time-to-first-audio (Parrot pattern). */
	tts_shorten_first_chunk?: boolean,
	/**  Audio format for saved TTS output. */
	tts_save_format?: AudioFormat,
	/**  Wake word / always-listening keyword detection. */
	wake_word?: WakeWordConfig,
};

/**  Which TTS engine synthesizes speech. */
export type TtsEngine = "piper" | "kokoro" | "kitten" | "pocket" | "sapi" | "openai" | "elevenlabs" | "cartesia";

export type TtsGreetingConfig = {
	text?: string,
	speed?: number | null,
	voice?: string,
	engine?: TtsEngine,
	/**  Speaking variability (Piper HTTP: noise_scale). 0=monotone, 0.667=Piper default. */
	noise_scale?: number | null,
	/**  Phoneme width variability (Piper HTTP: noise_w_scale). 0=precise, 0.8=Piper default. */
	noise_w_scale?: number | null,
};

export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool";

/**  Metadata for a voice option exposed in the settings UI. */
export type Voice = {
	id: string,
	name: string,
	language: string | null,
};

/**  User-facing configuration for wake word detection. */
export type WakeWordConfig = {
	enabled: boolean,
	keyword: string,
	threshold: number | null,
	show_indicator: boolean,
};

/**  Cursor trail / wgpu overlay effect configuration (CursorFX + TD_Web_Trail). */
export type WgpuTrailConfig = {
	/**  Master enable for the native wgpu cursor trail. */
	enabled?: boolean,
	/**  Trail colour as hex string (e.g. "#7c3aed"). */
	color?: string,
	/**  Number of trail segments (chain length). */
	segments?: number,
	/**  Spring stiffness for the physics chain (0.0–1.0). */
	spring?: number | null,
	/**  Velocity friction / damping (0.0–1.0). */
	friction?: number | null,
	/**  Base trail width in logical pixels at the head. */
	width?: number | null,
	/**  Width taper exponent (e.g. 1.5 = trail tapers toward tail). */
	taper?: number | null,
	/**  Opacity of the glow pass (0.0–1.0). */
	glow?: number | null,
	/**  Lazy-brush dead-zone radius in logical pixels. */
	lazy_radius?: number | null,
	/**  Lazy-brush friction factor (0.0–1.0). */
	lazy_friction?: number | null,
	/**  Enable cursor click ripple effect. */
	click_ripple?: boolean,
};

export type WhisperAcceleratorSetting = "auto" | "cpu" | "gpu";

export type WindowsMicrophonePermissionStatus = {
	supported: boolean,
	overall_access: PermissionAccess,
	device_access: PermissionAccess,
	app_access: PermissionAccess,
	desktop_app_access: PermissionAccess,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

