// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	changeBinding: (id: string, binding: string) => typedError<BindingResponse, string>(__TAURI_INVOKE("change_binding", { id, binding })),
	resetBinding: (id: string) => typedError<BindingResponse, string>(__TAURI_INVOKE("reset_binding", { id })),
	changeShortcutActivationSetting: (activation: ShortcutActivation) => typedError<null, string>(__TAURI_INVOKE("change_shortcut_activation_setting", { activation })),
	changeHoldThresholdMsSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_hold_threshold_ms_setting", { ms })),
	changeAudioFeedbackSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_audio_feedback_setting", { enabled })),
	changeAudioFeedbackVolumeSetting: (volume: number | null) => typedError<null, string>(__TAURI_INVOKE("change_audio_feedback_volume_setting", { volume })),
	changeSoundThemeSetting: (theme: string) => typedError<null, string>(__TAURI_INVOKE("change_sound_theme_setting", { theme })),
	changeThemeSetting: (theme: string) => typedError<null, string>(__TAURI_INVOKE("change_theme_setting", { theme })),
	changeCustomAccentColorSetting: (color: string | null) => typedError<null, string>(__TAURI_INVOKE("change_custom_accent_color_setting", { color })),
	changeUiScaleSetting: (scale: number | null) => typedError<null, string>(__TAURI_INVOKE("change_ui_scale_setting", { scale })),
	changeStartHiddenSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_start_hidden_setting", { enabled })),
	changeAutostartSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_autostart_setting", { enabled })),
	changeTranslateToEnglishSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_translate_to_english_setting", { enabled })),
	changeSelectedLanguageSetting: (language: string) => typedError<null, string>(__TAURI_INVOKE("change_selected_language_setting", { language })),
	changeOverlayPositionSetting: (position: string) => typedError<null, string>(__TAURI_INVOKE("change_overlay_position_setting", { position })),
	changeOverlayStyleSetting: (style: string) => typedError<null, string>(__TAURI_INVOKE("change_overlay_style_setting", { style })),
	changeOverlayDirectModeSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_overlay_direct_mode_setting", { enabled })),
	changeOverlayDirectSpeedSetting: (speed: number) => typedError<null, string>(__TAURI_INVOKE("change_overlay_direct_speed_setting", { speed })),
	changeOverlaySpeechStatsSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_overlay_speech_stats_setting", { enabled })),
	changeSpeechPauseHoldSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_speech_pause_hold_setting", { ms })),
	changeDirectStreamingSpeedSetting: (speed: number) => typedError<null, string>(__TAURI_INVOKE("change_direct_streaming_speed_setting", { speed })),
	changeDebugModeSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_debug_mode_setting", { enabled })),
	changeWordCorrectionThresholdSetting: (threshold: number | null) => typedError<null, string>(__TAURI_INVOKE("change_word_correction_threshold_setting", { threshold })),
	changeExtraRecordingBufferSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_extra_recording_buffer_setting", { ms })),
	changePasteDelayMsSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_paste_delay_ms_setting", { ms })),
	changePasteDelayAfterMsSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_paste_delay_after_ms_setting", { ms })),
	changeReliablePasteSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_reliable_paste_setting", { enabled })),
	changePasteMethodSetting: (method: string) => typedError<null, string>(__TAURI_INVOKE("change_paste_method_setting", { method })),
	getAvailableTypingTools: () => __TAURI_INVOKE<string[]>("get_available_typing_tools"),
	changeTypingToolSetting: (tool: string) => typedError<null, string>(__TAURI_INVOKE("change_typing_tool_setting", { tool })),
	changeExternalScriptPathSetting: (path: string | null) => typedError<null, string>(__TAURI_INVOKE("change_external_script_path_setting", { path })),
	changeClipboardHandlingSetting: (handling: string) => typedError<null, string>(__TAURI_INVOKE("change_clipboard_handling_setting", { handling })),
	changeAutoSubmitSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_auto_submit_setting", { enabled })),
	changeAutoSubmitKeySetting: (key: string) => typedError<null, string>(__TAURI_INVOKE("change_auto_submit_key_setting", { key })),
	changeMultiSttEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_enabled_setting", { enabled })),
	changeMultiSttExtraModel: (slot: number, modelId: string | null) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_extra_model", { slot, modelId })),
	changeMultiSttExtraModelLanguage: (slot: number, language: string | null) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_extra_model_language", { slot, language })),
	changeMultiSttMergePrompt: (prompt: {
	id: string,
	name: string,
	prompt: string,
} | null) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_merge_prompt", { prompt })),
	changeMultiSttTranslateModel2: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_translate_model_2", { enabled })),
	changeMultiSttTranslateModel3: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_translate_model_3", { enabled })),
	changeMultiSttTranslateModel4: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_translate_model_4", { enabled })),
	changeMultiSttKeepExtraModelsLoadedSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_keep_extra_models_loaded_setting", { enabled })),
	changeMultiSttPerformanceModeEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_performance_mode_enabled_setting", { enabled })),
	changeMultiSttPerformanceModeTriggerOnStartSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_performance_mode_trigger_on_start_setting", { enabled })),
	changeMultiSttPerformanceModeFullPowerShortcut: (shortcut: string) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_performance_mode_full_power_shortcut", { shortcut })),
	changeMultiSttPerformanceModeNormalShortcut: (shortcut: string) => typedError<null, string>(__TAURI_INVOKE("change_multi_stt_performance_mode_normal_shortcut", { shortcut })),
	changeMicIdleTimeoutSettings: (value: number, unit: MicIdleTimeoutUnit, infinite: boolean) => typedError<null, string>(__TAURI_INVOKE("change_mic_idle_timeout_settings", { value, unit, infinite })),
	changePostProcessEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_post_process_enabled_setting", { enabled })),
	changeExperimentalEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_experimental_enabled_setting", { enabled })),
	changePostProcessBaseUrlSetting: (providerId: string, baseUrl: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl })),
	changePostProcessApiKeySetting: (providerId: string, apiKey: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey })),
	changePostProcessModelSetting: (providerId: string, model: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_model_setting", { providerId, model })),
	setPostProcessProvider: (providerId: string) => typedError<null, string>(__TAURI_INVOKE("set_post_process_provider", { providerId })),
	fetchPostProcessModels: (providerId: string) => typedError<string[], string>(__TAURI_INVOKE("fetch_post_process_models", { providerId })),
	addPostProcessPrompt: (name: string, prompt: string) => typedError<LLMPrompt, string>(__TAURI_INVOKE("add_post_process_prompt", { name, prompt })),
	updatePostProcessPrompt: (id: string, name: string, prompt: string) => typedError<null, string>(__TAURI_INVOKE("update_post_process_prompt", { id, name, prompt })),
	deletePostProcessPrompt: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_post_process_prompt", { id })),
	setPostProcessSelectedPrompt: (id: string) => typedError<null, string>(__TAURI_INVOKE("set_post_process_selected_prompt", { id })),
	updateCustomWords: (words: string[]) => typedError<null, string>(__TAURI_INVOKE("update_custom_words", { words })),
	/**
	 *  Temporarily unregister all bindings while the user is recording a
	 *  shortcut in the UI. This avoids firing actions while keys are recorded.
	 */
	suspendAllBindings: () => typedError<null, string>(__TAURI_INVOKE("suspend_all_bindings")),
	/**  Re-register all bindings after the user has finished recording. */
	resumeAllBindings: () => typedError<null, string>(__TAURI_INVOKE("resume_all_bindings")),
	changeMuteWhileRecordingSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_mute_while_recording_setting", { enabled })),
	changeAppendTrailingSpaceSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_append_trailing_space_setting", { enabled })),
	changeAppendTrailingNewlineSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_append_trailing_newline_setting", { enabled })),
	changeLazyStreamCloseSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_lazy_stream_close_setting", { enabled })),
	changeSaveRawAudioSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_save_raw_audio_setting", { enabled })),
	changeVadEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_vad_enabled_setting", { enabled })),
	/**
	 *  Persist the overlay's scope picture (`overlay_scope`), refresh the cached
	 *  geometry the show path sizes the window with, hand the waveform window
	 *  to the analyser and re-place a visible overlay.
	 */
	changeOverlayScopeSettings: (scope: OverlayScopeSettings) => typedError<null, string>(__TAURI_INVOKE("change_overlay_scope_settings", { scope })),
	/**
	 *  Toggle RNNoise suppression. Persisted for future recorders and pushed to
	 *  the live one, which switches paths on its next chunk.
	 */
	changeDenoiseEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_denoise_enabled_setting", { enabled })),
	/**  RNNoise wet/dry strength (0–1). */
	changeDenoiseStrengthSetting: (strength: number | null) => typedError<null, string>(__TAURI_INVOKE("change_denoise_strength_setting", { strength })),
	/**  RNNoise's own speech-probability gate threshold (0–1, 0 = off). */
	changeDenoiseVadThresholdSetting: (threshold: number | null) => typedError<null, string>(__TAURI_INVOKE("change_denoise_vad_threshold_setting", { threshold })),
	/**  Grace period of that gate, in milliseconds. */
	changeDenoiseVadGraceSetting: (graceMs: number) => typedError<null, string>(__TAURI_INVOKE("change_denoise_vad_grace_setting", { graceMs })),
	changeFillerWordRemovalEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_filler_word_removal_enabled_setting", { enabled })),
	changeAppLanguageSetting: (language: string) => typedError<null, string>(__TAURI_INVOKE("change_app_language_setting", { language })),
	changeUpdateChecksSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_update_checks_setting", { enabled })),
	changeShowWhatsNewOnUpdateSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_show_whats_new_on_update_setting", { enabled })),
	changeWhatsNewLastSeenVersionSetting: (version: string) => typedError<null, string>(__TAURI_INVOKE("change_whats_new_last_seen_version_setting", { version })),
	/**
	 *  Change the keyboard implementation with runtime switching.
	 *  This will unregister all shortcuts from the old implementation,
	 *  validate shortcuts for the new implementation (resetting invalid ones to defaults),
	 *  and register them with the new implementation.
	 */
	changeKeyboardImplementationSetting: (implementation: string) => typedError<ImplementationChangeResult, string>(__TAURI_INVOKE("change_keyboard_implementation_setting", { implementation })),
	/**  Get the current keyboard implementation */
	getKeyboardImplementation: () => __TAURI_INVOKE<string>("get_keyboard_implementation"),
	changeShowTrayIconSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_show_tray_icon_setting", { enabled })),
	changeTranscribeAcceleratorSetting: (accelerator: TranscribeAcceleratorSetting) => typedError<null, string>(__TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator })),
	changeTranscribeGpuDevice: (device: string | null) => typedError<null, string>(__TAURI_INVOKE("change_transcribe_gpu_device", { device })),
	/**
	 *  Return which accelerators and GPU devices are available for this build.
	 * 
	 *  First-call cost is dominated by enumerating GPU devices through the
	 *  transcribe.cpp Metal/CUDA backend, which loads dynamic libraries and
	 *  probes hardware. Run it on the blocking pool so the webview thread
	 *  stays responsive — see also the startup pre-warm in `lib.rs`.
	 */
	getAvailableAccelerators: () => __TAURI_INVOKE<AvailableAccelerators>("get_available_accelerators"),
	/**  Start key recording mode */
	startHandyKeysRecording: (bindingId: string) => typedError<null, string>(__TAURI_INVOKE("start_handy_keys_recording", { bindingId })),
	/**  Stop key recording mode */
	stopHandyKeysRecording: () => typedError<null, string>(__TAURI_INVOKE("stop_handy_keys_recording")),
	getSecureInputStatus: () => __TAURI_INVOKE<SecureInputStatus>("get_secure_input_status"),
	runKeyboardDiagnostic: (durationSecs: number | null) => typedError<KeyboardDiagnosticReport, string>(__TAURI_INVOKE("run_keyboard_diagnostic", { durationSecs })),
	triggerUpdateCheck: () => typedError<null, string>(__TAURI_INVOKE("trigger_update_check")),
	showMainWindowCommand: () => typedError<null, string>(__TAURI_INVOKE("show_main_window_command")),
	cancelOperation: () => __TAURI_INVOKE<void>("cancel_operation"),
	isPortable: () => __TAURI_INVOKE<boolean>("is_portable"),
	/**
	 *  Start the live VAD test from Settings → Advanced: microphone + detector
	 *  only, streaming `VadTestEvent`s. No model is involved.
	 */
	startVadTest: () => typedError<null, string>(__TAURI_INVOKE("start_vad_test")),
	/**  Stop the live VAD test and discard its audio. */
	stopVadTest: () => typedError<null, string>(__TAURI_INVOKE("stop_vad_test")),
	getLlamaServerState: () => __TAURI_INVOKE<LlamaServerStateEvent>("get_llama_server_state"),
	getLlamaServerLogs: () => __TAURI_INVOKE<string[]>("get_llama_server_logs"),
	startLlamaServer: () => typedError<null, string>(__TAURI_INVOKE("start_llama_server")),
	stopLlamaServer: () => typedError<null, string>(__TAURI_INVOKE("stop_llama_server")),
	restartLlamaServer: () => typedError<null, string>(__TAURI_INVOKE("restart_llama_server")),
	/**
	 *  Persist the llama settings. A running server keeps its current command
	 *  line until it is restarted; the UI offers that explicitly.
	 */
	changeLlamaSettings: (settings: LlamaSettings) => typedError<null, string>(__TAURI_INVOKE("change_llama_settings", { settings })),
	/**  The command line the current settings would launch, for the page preview. */
	getLlamaCommandPreview: () => typedError<string, string>(__TAURI_INVOKE("get_llama_command_preview")),
	listGgufFiles: (dir: string) => __TAURI_INVOKE<GgufFile[]>("list_gguf_files", { dir }),
	detectLlamaInstall: () => __TAURI_INVOKE<{
	server_dir: string,
	model_path: string | null,
	draft_model_path: string | null,
	mmproj_path: string | null,
} | null>("detect_llama_install"),
	applyLlamaToPostProcessing: () => typedError<null, string>(__TAURI_INVOKE("apply_llama_to_post_processing")),
	fetchLlamaReleases: (channel: string, force: boolean) => typedError<LlamaRelease[], string>(__TAURI_INVOKE("fetch_llama_releases", { channel, force })),
	detectLlamaBackend: () => __TAURI_INVOKE<string>("detect_llama_backend"),
	listInstalledLlamaServers: () => __TAURI_INVOKE<InstalledLlamaServer[]>("list_installed_llama_servers"),
	/**
	 *  Download + unpack a release; progress arrives as `LlamaDownloadEvent`.
	 *  Runs to completion in the background so the page can navigate away.
	 */
	installLlamaRelease: (tag: string, backend: string, includeCudart: boolean) => typedError<null, string>(__TAURI_INVOKE("install_llama_release", { tag, backend, includeCudart })),
	removeInstalledLlamaServer: (dir: string) => typedError<null, string>(__TAURI_INVOKE("remove_installed_llama_server", { dir })),
	/**  The installed CUDA toolkit whose runtime DLLs a CUDA build can use. */
	detectCudaToolkit: () => __TAURI_INVOKE<{
	/**
	 *  Folder that holds `cudart64_*.dll` (CUDA 13 keeps it in `bin\x64`,
	 *  CUDA 12 and older in `bin`).
	 */
	runtime_dir: string,
	/**  Toolkit version as the installer names it (`13.3`), when known. */
	version: string | null,
	/**
	 *  Whether `runtime_dir` is on the PATH Handy was started with. When it is
	 *  not, `LlamaServerManager::start` prepends it to the child's PATH.
	 */
	on_path: boolean,
	/**
	 *  Whether cuBLAS (`cublas64_*` + `cublasLt64_*`) sits next to cudart —
	 *  llama.cpp's CUDA backend needs both.
	 */
	has_cublas: boolean,
} | null>("detect_cuda_toolkit"),
	/**  Delete the bundled cudart/cuBLAS DLLs from an install; returns MB freed. */
	removeBundledCudaRuntime: (dir: string) => typedError<number, string>(__TAURI_INVOKE("remove_bundled_cuda_runtime", { dir })),
	/**
	 *  The most recent sample, so a footer that mounts between ticks does not
	 *  show empty meters for up to a second.
	 */
	getSystemStats: () => __TAURI_INVOKE<{
	cpu_percent: number | null,
	mem_used_mb: number,
	mem_total_mb: number,
	gpu_name: string | null,
	gpu_percent: number | null,
	vram_used_mb: number | null,
	vram_total_mb: number | null,
	gpu_temp_c: number | null,
} | null>("get_system_stats"),
	isUpdateChecksLocked: () => __TAURI_INVOKE<boolean>("is_update_checks_locked"),
	getAppDirPath: () => typedError<string, string>(__TAURI_INVOKE("get_app_dir_path")),
	getAppSettings: () => typedError<AppSettings_Serialize, string>(__TAURI_INVOKE("get_app_settings")),
	getDefaultSettings: () => typedError<AppSettings_Serialize, string>(__TAURI_INVOKE("get_default_settings")),
	getLogDirPath: () => typedError<string, string>(__TAURI_INVOKE("get_log_dir_path")),
	setLogLevel: (level: LogLevel) => typedError<null, string>(__TAURI_INVOKE("set_log_level", { level })),
	openRecordingsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_recordings_folder")),
	openModelsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_models_folder")),
	openPluginsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_plugins_folder")),
	openLogDir: () => typedError<null, string>(__TAURI_INVOKE("open_log_dir")),
	openAppDataDir: () => typedError<null, string>(__TAURI_INVOKE("open_app_data_dir")),
	/**
	 *  Check if Apple Intelligence is available on this device.
	 *  Called by the frontend when the user selects Apple Intelligence provider.
	 */
	checkAppleIntelligenceAvailable: () => __TAURI_INVOKE<boolean>("check_apple_intelligence_available"),
	/**
	 *  Try to initialize Enigo (keyboard/mouse simulation).
	 *  On macOS, this will return an error if accessibility permissions are not granted.
	 */
	initializeEnigo: () => typedError<null, string>(__TAURI_INVOKE("initialize_enigo")),
	/**
	 *  Initialize keyboard shortcuts.
	 *  On macOS, this should be called after accessibility permissions are granted.
	 *  This is idempotent - calling it multiple times is safe.
	 */
	initializeShortcuts: () => typedError<null, string>(__TAURI_INVOKE("initialize_shortcuts")),
	getArchPlugins: () => typedError<ArchPluginInfo[], string>(__TAURI_INVOKE("get_arch_plugins")),
	loadArchPlugin: (path: string) => typedError<null, string>(__TAURI_INVOKE("load_arch_plugin", { path })),
	registerArchDir: (dir: string) => typedError<null, string>(__TAURI_INVOKE("register_arch_dir", { dir })),
	getAvailableModels: () => typedError<ModelInfo[], string>(__TAURI_INVOKE("get_available_models")),
	getModelInfo: (modelId: string) => typedError<{
	id: string,
	name: string,
	description: string,
	filename: string,
	source: ModelSource,
	size_mb: number,
	is_downloaded: boolean,
	is_downloading: boolean,
	partial_size: number | null,
	accuracy_score: number | null,
	speed_score: number | null,
	supports_translation: boolean,
	is_recommended: boolean,
	supported_languages: string[],
	supports_language_selection: boolean,
	is_custom: boolean,
	supports_streaming: boolean,
	supports_language_detection: boolean,
	/**
	 *  Which native streaming latency extension the model supports (if any).
	 *  Populated for catalog streaming models; `None` for legacy/custom.
	 */
	native_streaming_latency_kind?: NativeStreamingLatencyKind | null,
} | null, string>(__TAURI_INVOKE("get_model_info", { modelId })),
	downloadModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("download_model", { modelId })),
	downloadModelQuant: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("download_model_quant", { modelId })),
	getModelQuantVariants: (modelId: string) => typedError<QuantVariant[], string>(__TAURI_INVOKE("get_model_quant_variants", { modelId })),
	changeNativeStreamingLatencyPresetSetting: (modelId: string, preset: NativeStreamingLatencyPreset) => typedError<null, string>(__TAURI_INVOKE("change_native_streaming_latency_preset_setting", { modelId, preset })),
	deleteModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("delete_model", { modelId })),
	cancelDownload: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_download", { modelId })),
	setActiveModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("set_active_model", { modelId })),
	getCurrentModel: () => typedError<string, string>(__TAURI_INVOKE("get_current_model")),
	getTranscriptionModelStatus: () => typedError<string | null, string>(__TAURI_INVOKE("get_transcription_model_status")),
	isModelLoading: () => typedError<boolean, string>(__TAURI_INVOKE("is_model_loading")),
	/**
	 *  Re-scan local sources (custom models dir + shared HF cache) for models added
	 *  since launch
	 */
	rescanLocalModels: () => typedError<null, string>(__TAURI_INVOKE("rescan_local_models")),
	/**
	 *  Benchmark all downloaded quantization variants of the model identified by
	 *  `model_id`.  Uses the latest completed recording as the reference audio.
	 * 
	 *  For each downloaded quant (e.g. Q4_K_M, Q5_K_M, Q8_0) the model is loaded
	 *  on a temporary engine, a warmup transcription is discarded, three timed
	 *  transcriptions are averaged, and the engine is dropped before the next
	 *  variant.  Progress events are emitted on the `benchmark-progress` channel
	 *  and the full result vector is returned when all variants are done.
	 */
	benchmarkModelQuantizations: (modelId: string) => typedError<BenchmarkResult[], string>(__TAURI_INVOKE("benchmark_model_quantizations", { modelId })),
	/**
	 *  Benchmark a single quantization variant of the current model.
	 *  Uses the latest completed recording as the reference audio.
	 * 
	 *  The engine is loaded from a clean state (primary model unloaded first),
	 *  a warmup transcription is discarded, three timed runs are averaged,
	 *  and the engine is dropped after the run.
	 */
	benchmarkSingleQuantization: (modelId: string) => typedError<BenchmarkResult, string>(__TAURI_INVOKE("benchmark_single_quantization", { modelId })),
	updateMicrophoneMode: (alwaysOn: boolean) => typedError<null, string>(__TAURI_INVOKE("update_microphone_mode", { alwaysOn })),
	getMicrophoneMode: () => typedError<boolean, string>(__TAURI_INVOKE("get_microphone_mode")),
	getWindowsMicrophonePermissionStatus: () => __TAURI_INVOKE<WindowsMicrophonePermissionStatus>("get_windows_microphone_permission_status"),
	openMicrophonePrivacySettings: () => typedError<null, string>(__TAURI_INVOKE("open_microphone_privacy_settings")),
	getAvailableMicrophones: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("get_available_microphones")),
	setSelectedMicrophone: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_selected_microphone", { deviceName })),
	getSelectedMicrophone: () => typedError<string, string>(__TAURI_INVOKE("get_selected_microphone")),
	getAvailableOutputDevices: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("get_available_output_devices")),
	setSelectedOutputDevice: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_selected_output_device", { deviceName })),
	getSelectedOutputDevice: () => typedError<string, string>(__TAURI_INVOKE("get_selected_output_device")),
	playTestSound: (soundType: string) => __TAURI_INVOKE<void>("play_test_sound", { soundType }),
	checkCustomSounds: () => __TAURI_INVOKE<CustomSounds>("check_custom_sounds"),
	setClamshellMicrophone: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_clamshell_microphone", { deviceName })),
	getClamshellMicrophone: () => typedError<string, string>(__TAURI_INVOKE("get_clamshell_microphone")),
	isRecording: () => __TAURI_INVOKE<boolean>("is_recording"),
	getMicrophoneChannels: (deviceName: string) => typedError<number, string>(__TAURI_INVOKE("get_microphone_channels", { deviceName })),
	setSelectedChannel: (channel: number | null) => typedError<null, string>(__TAURI_INVOKE("set_selected_channel", { channel })),
	setModelUnloadTimeout: (timeout: ModelUnloadTimeout) => __TAURI_INVOKE<void>("set_model_unload_timeout", { timeout }),
	getModelLoadStatus: () => typedError<ModelLoadStatus, string>(__TAURI_INVOKE("get_model_load_status")),
	unloadModelManually: () => typedError<null, string>(__TAURI_INVOKE("unload_model_manually")),
	unloadExtraModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("unload_extra_model", { modelId })),
	getExtraLoadedModels: () => typedError<string[], string>(__TAURI_INVOKE("get_extra_loaded_models")),
	loadExtraModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("load_extra_model", { modelId })),
	getHistoryEntries: (cursor: number | null, limit: number | null) => typedError<PaginatedHistory, string>(__TAURI_INVOKE("get_history_entries", { cursor, limit })),
	toggleHistoryEntrySaved: (id: number) => typedError<null, string>(__TAURI_INVOKE("toggle_history_entry_saved", { id })),
	getAudioFilePath: (fileName: string) => typedError<string, string>(__TAURI_INVOKE("get_audio_file_path", { fileName })),
	deleteHistoryEntry: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_history_entry", { id })),
	deleteAllRecordings: () => typedError<null, string>(__TAURI_INVOKE("delete_all_recordings")),
	retryHistoryEntryTranscription: (id: number) => typedError<null, string>(__TAURI_INVOKE("retry_history_entry_transcription", { id })),
	postProcessHistoryEntry: (id: number) => typedError<null, string>(__TAURI_INVOKE("post_process_history_entry", { id })),
	multiSttHistoryEntry: (id: number) => typedError<null, string>(__TAURI_INVOKE("multi_stt_history_entry", { id })),
	updateHistoryLimit: (limit: number) => typedError<null, string>(__TAURI_INVOKE("update_history_limit", { limit })),
	updateRecordingRetentionPeriod: (period: string) => typedError<null, string>(__TAURI_INVOKE("update_recording_retention_period", { period })),
	/**
	 *  Return the most recent history entry with non-empty transcription text,
	 *  so the frontend can tell the user which recording will be used as the
	 *  benchmark reference before starting the run.
	 */
	getLatestRecordingInfo: () => typedError<{
	id: number,
	file_name: string,
	timestamp: number | null,
	saved: boolean,
	title: string,
	transcription_text: string,
	post_processed_text: string | null,
	post_process_prompt: string | null,
	post_process_requested: boolean,
	model_id: string | null,
	engine: string | null,
	audio_duration_ms: number | null,
	speech_duration_ms: number | null,
	sample_rate_hz: number | null,
	word_count: number | null,
	transcription_latency_ms: number | null,
	post_processing_latency_ms: number | null,
	language: string | null,
	mode: string | null,
	extra_models: string[] | null,
} | null, string>(__TAURI_INVOKE("get_latest_recording_info")),
	getStatisticsSummary: (range: StatisticsRange) => typedError<StatisticsSummary, string>(__TAURI_INVOKE("get_statistics_summary", { range })),
	resetStatistics: () => typedError<null, string>(__TAURI_INVOKE("reset_statistics")),
	/**
	 *  Stub implementation for non-macOS platforms
	 *  Always returns false since laptop detection is macOS-specific
	 */
	isLaptop: () => typedError<boolean, string>(__TAURI_INVOKE("is_laptop")),
	/**
	 *  Set the speech-probability threshold of the VAD. The persisted value is
	 *  what a freshly built recorder reads; the live detector takes the new
	 *  threshold in place on its next frame, so this works while recording and
	 *  while the live VAD test runs, with nothing to reopen or roll back.
	 */
	changeVadThresholdSetting: (threshold: number | null) => typedError<null, string>(__TAURI_INVOKE("change_vad_threshold_setting", { threshold })),
	changeFileTranscriptionSettings: (settings: FileTranscriptionSettings) => typedError<null, string>(__TAURI_INVOKE("change_file_transcription_settings", { settings })),
	listAudioFilesInFolder: (folder: string, includeSubfolders: boolean) => typedError<string[], string>(__TAURI_INVOKE("list_audio_files_in_folder", { folder, includeSubfolders })),
	startFileTranscription: (paths: string[]) => typedError<number, string>(__TAURI_INVOKE("start_file_transcription", { paths })),
	cancelFileTranscription: () => __TAURI_INVOKE<void>("cancel_file_transcription"),
	getFileTranscriptionStatus: () => __TAURI_INVOKE<FileTranscriptionStatus>("get_file_transcription_status"),
	/**
	 *  Show `path` in the OS file manager: folders are opened, files are revealed
	 *  (selected) inside their folder.
	 */
	revealPathInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_path_in_file_manager", { path })),
	/**
	 *  Read a UTF-8 text file (transcript viewer). Invalid UTF-8 is replaced
	 *  rather than rejected so a partially written live transcript still shows.
	 */
	readTextFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_text_file", { path })),
	changeLiveModeSettings: (settings: LiveModeSettings) => typedError<null, string>(__TAURI_INVOKE("change_live_mode_settings", { settings })),
	liveModeStart: () => typedError<null, string>(__TAURI_INVOKE("live_mode_start")),
	liveModeStop: () => typedError<null, string>(__TAURI_INVOKE("live_mode_stop")),
	liveModeStatus: () => __TAURI_INVOKE<LiveModeStatus>("live_mode_status"),
	/**  Past sessions under the configured output folder, newest first. */
	liveModeListSessions: () => typedError<LiveSessionInfo[], string>(__TAURI_INVOKE("live_mode_list_sessions")),
	/**  The folder used when no output folder is configured, for display. */
	liveModeDefaultOutputDir: () => typedError<string, string>(__TAURI_INVOKE("live_mode_default_output_dir")),
	/**
	 *  Persist the page's parameters and hand them to the running analysis,
	 *  which applies them on its next frame. A threading-mode change restarts
	 *  the session, which can reopen the microphone, so the hand-off runs on a
	 *  blocking thread.
	 */
	changeLiveFftSettings: (settings: LiveFftSettings) => typedError<null, string>(__TAURI_INVOKE("change_live_fft_settings", { settings })),
	/**
	 *  Start the analyser: opens the microphone (a device open can block, so
	 *  this stays off the webview thread) and streams `LiveFftFrameEvent`s.
	 */
	liveFftStart: () => typedError<null, string>(__TAURI_INVOKE("live_fft_start")),
	liveFftStop: () => typedError<null, string>(__TAURI_INVOKE("live_fft_stop")),
	liveFftStatus: () => __TAURI_INVOKE<LiveFftStatus>("live_fft_status"),
	/**  The page's Reset button: clears ballistics, AGC and EQ state. */
	liveFftReset: () => __TAURI_INVOKE<void>("live_fft_reset"),
	/**  The "Raw" preset: linear magnitude, frame-peak reference, no ballistics. */
	liveFftRawDefaults: () => __TAURI_INVOKE<LiveFftSettings>("live_fft_raw_defaults"),
};

/** Events */
export const events = {
	fileTranscriptionEvent: makeEvent<FileTranscriptionEvent>("file-transcription-event"),
	historyUpdatePayload: makeEvent<HistoryUpdatePayload>("history-update-payload"),
	liveFftFrameEvent: makeEvent<LiveFftFrameEvent>("live-fft-frame-event"),
	liveFftStateEvent: makeEvent<LiveFftStateEvent>("live-fft-state-event"),
	liveModeStateEvent: makeEvent<LiveModeStateEvent>("live-mode-state-event"),
	liveModeTranscriptEvent: makeEvent<LiveModeTranscriptEvent>("live-mode-transcript-event"),
	llamaDownloadEvent: makeEvent<LlamaDownloadEvent>("llama-download-event"),
	llamaServerStateEvent: makeEvent<LlamaServerStateEvent>("llama-server-state-event"),
	speechActivityEvent: makeEvent<SpeechActivityEvent>("speech-activity-event"),
	statisticsUpdatedEvent: makeEvent<StatisticsUpdatedEvent>("statistics-updated-event"),
	streamPhaseEvent: makeEvent<StreamPhaseEvent_Deserialize>("stream-phase-event"),
	streamTextEvent: makeEvent<StreamTextEvent>("stream-text-event"),
	systemStatsEvent: makeEvent<SystemStatsEvent>("system-stats-event"),
	vadTestEvent: makeEvent<VadTestEvent>("vad-test-event"),
};

/* Types */
/**
 *  The container-level `serde(default)` (backed by the `Default` impl below)
 *  guarantees every field — including ones added in the future — falls back to
 *  its `get_default_settings()` value when missing from a stored settings
 *  object, so a partial store can never fail the whole load (#1619).
 *  Field-level defaults below take precedence where present.
 */
export type AppSettings = AppSettings_Serialize | AppSettings_Deserialize;

/**
 *  The container-level `serde(default)` (backed by the `Default` impl below)
 *  guarantees every field — including ones added in the future — falls back to
 *  its `get_default_settings()` value when missing from a stored settings
 *  object, so a partial store can never fail the whole load (#1619).
 *  Field-level defaults below take precedence where present.
 */
export type AppSettings_Deserialize = {
	/**
	 *  Internal settings schema marker for one-time migrations. Fresh installs
	 *  start at the current version; existing stores missing this key are
	 *  treated as version 0 and migrated forward.
	 */
	settings_schema_version?: number,
	/**
	 *  Defaults to empty on partial stores; the load path merges in the
	 *  default bindings for any missing keys before the settings are used.
	 */
	bindings?: { [key in string]: ShortcutBinding },
	/**
	 *  Replaces the pre-0.10 `push_to_talk` bool; stores missing this key are
	 *  migrated from it in `apply_settings_migrations`.
	 */
	shortcut_activation?: ShortcutActivation,
	/**
	 *  Hold-or-toggle only: a press held at least this long is push-to-talk,
	 *  anything shorter is a tap that locks recording on.
	 */
	hold_threshold_ms?: number,
	audio_feedback?: boolean,
	audio_feedback_volume?: number | null,
	sound_theme?: SoundTheme,
	start_hidden?: boolean,
	autostart_enabled?: boolean,
	update_checks_enabled?: boolean,
	show_whats_new_on_update?: boolean,
	/**
	 *  The app version whose What's New the user has already seen. Fresh installs
	 *  default to the current version (nothing is "new" to them). Existing users
	 *  upgrading from before this key existed are blanked by the migration so they
	 *  see the current release's notes — see `apply_settings_migrations`.
	 */
	whats_new_last_seen_version?: string,
	selected_model?: string,
	onboarding_completed?: boolean,
	always_on_microphone?: boolean,
	selected_microphone?: string | null,
	/**
	 *  Which input channel to use on the selected microphone device.
	 *  None means "average all channels" (original behavior).
	 */
	selected_channel?: number | null,
	clamshell_microphone?: string | null,
	selected_output_device?: string | null,
	translate_to_english?: boolean,
	selected_language?: string,
	overlay_position?: OverlayPosition_Deserialize,
	debug_mode?: boolean,
	log_level?: LogLevel,
	custom_words?: string[],
	model_unload_timeout?: ModelUnloadTimeout,
	word_correction_threshold?: number | null,
	history_limit?: number,
	recording_retention_period?: RecordingRetentionPeriod,
	save_raw_audio?: boolean,
	paste_method?: PasteMethod,
	clipboard_handling?: ClipboardHandling,
	auto_submit?: boolean,
	auto_submit_key?: AutoSubmitKey,
	post_process_enabled?: boolean,
	post_process_provider_id?: string,
	post_process_providers?: PostProcessProvider[],
	post_process_api_keys?: SecretMap,
	post_process_models?: { [key in string]: string },
	post_process_prompts?: LLMPrompt[],
	post_process_selected_prompt_id?: string | null,
	mute_while_recording?: boolean,
	append_trailing_space?: boolean,
	append_trailing_newline?: boolean,
	app_language?: string,
	theme?: Theme,
	custom_accent_color?: string | null,
	/**
	 *  Zoom of the settings window (0.7–1.6, 1.0 = native), for screens whose
	 *  OS scaling makes the UI too small or too large. Applied as CSS zoom.
	 */
	ui_scale?: number | null,
	experimental_enabled?: boolean,
	lazy_stream_close?: boolean,
	keyboard_implementation?: KeyboardImplementation,
	show_tray_icon?: boolean,
	paste_delay_ms?: number,
	paste_delay_after_ms?: number,
	/**
	 *  Debug-gated ("beta") receipt-sequenced paste: restore the clipboard only
	 *  after the target app actually reads the transcript, instead of after a
	 *  fixed delay. See `paste_tx`. macOS and Windows only.
	 */
	reliable_paste?: boolean,
	typing_tool?: TypingTool,
	external_script_path?: string | null,
	filler_word_removal_enabled?: boolean,
	custom_filler_words?: string[] | null,
	transcribe_accelerator?: TranscribeAcceleratorSetting,
	/**
	 *  Stable transcribe.cpp device selector. This is derived from the backend's
	 *  `device_id` when available (or its name for backends such as Metal),
	 *  never from the process-local device registry index.
	 */
	transcribe_gpu_device?: string | null,
	extra_recording_buffer_ms?: number,
	vad_enabled?: boolean,
	/**
	 *  RNNoise noise suppression on the microphone path, before the VAD and
	 *  the model (`audio_toolkit::audio::DenoiseChain`). Off by default: it
	 *  adds a little latency and can make some voices sound processed; the
	 *  live VAD test in Settings → Advanced shows its effect.
	 */
	denoise_enabled?: boolean,
	/**
	 *  RNNoise wet/dry mix (0–1): 1 = the suppressor's output, 0 = the input
	 *  untouched.
	 */
	denoise_strength?: number | null,
	/**
	 *  RNNoise's own speech probability below which the suppressor mutes
	 *  the frame (0–1); 0 turns the gate off.
	 */
	denoise_vad_threshold?: number | null,
	/**
	 *  How long audio keeps passing after the last frame above that
	 *  threshold, in milliseconds.
	 */
	denoise_vad_grace_ms?: number,
	/**  Speech-probability threshold of the Earshot detector (0.05–0.95). */
	vad_threshold_earshot?: number | null,
	/**
	 *  Which recording overlay to show: None / Minimal / Live. Streaming mode is
	 *  not gated on this — that follows model capability. Migrated from the old
	 *  `overlay_position` (position `none` → style `None`).
	 */
	overlay_style?: OverlayStyle,
	/**
	 *  Whether the live streaming overlay should reveal text character-by-character
	 *  in direct/typewriter mode instead of chunk-by-chunk / word-by-word.
	 */
	overlay_direct_mode?: boolean,
	/**  Speed at which characters appear in direct streaming mode (characters per second). */
	overlay_direct_speed?: number,
	/**  Speed at which characters are typed in direct streaming paste method (characters per second). */
	direct_streaming_speed?: number,
	/**
	 *  Whether the overlay shows live speech statistics: a speech/silence
	 *  indicator, a timer that counts only while you are actually speaking, and
	 *  the running average words per minute. Applies to both the Minimal and
	 *  Live overlays; ignored when the overlay is off.
	 */
	overlay_speech_stats?: boolean,
	/**
	 *  How long silence must last before the speech timer stops counting.
	 *  Shorter gaps are treated as part of the same utterance, so the timer does
	 *  not stall on the pauses between words.
	 */
	speech_pause_hold_ms?: number,
	multi_stt_enabled?: boolean,
	multi_stt_model_2?: string | null,
	multi_stt_model_3?: string | null,
	multi_stt_model_4?: string | null,
	multi_stt_language_model_2?: string | null,
	multi_stt_language_model_3?: string | null,
	multi_stt_language_model_4?: string | null,
	multi_stt_translate_model_2?: boolean,
	multi_stt_translate_model_3?: boolean,
	multi_stt_translate_model_4?: boolean,
	multi_stt_keep_extra_models_loaded?: boolean,
	multi_stt_merge_prompt?: LLMPrompt | null,
	/**
	 *  Multi-STT Performance Mode: when enabled, simulate a keyboard shortcut
	 *  to boost CPU performance before transcription starts (FULL POWER) and
	 *  restore normal power after the merge/paste completes.
	 */
	multi_stt_performance_mode_enabled?: boolean,
	multi_stt_performance_mode_trigger_on_start?: boolean,
	multi_stt_performance_mode_full_power_shortcut?: string,
	multi_stt_performance_mode_normal_shortcut?: string,
	mic_idle_timeout_value?: number,
	mic_idle_timeout_unit?: MicIdleTimeoutUnit,
	mic_idle_infinite?: boolean,
	native_streaming_latency_presets?: { [key in string]: NativeStreamingLatencyPreset },
	/**  "Transcribe Files" page (fork feature). */
	file_transcription?: FileTranscriptionSettings,
	/**  "Live Mode" page (fork feature). */
	live_mode?: LiveModeSettings,
	/**  "Live FFT" page (fork feature). */
	live_fft?: LiveFftSettings,
	/**
	 *  The recording overlay's picture of the microphone (which views, style,
	 *  waveform window, size); the analysis follows `live_fft`.
	 */
	overlay_scope?: OverlayScopeSettings,
	/**  In-app llama.cpp server (fork feature). */
	llama?: LlamaSettings,
};

/**
 *  The container-level `serde(default)` (backed by the `Default` impl below)
 *  guarantees every field — including ones added in the future — falls back to
 *  its `get_default_settings()` value when missing from a stored settings
 *  object, so a partial store can never fail the whole load (#1619).
 *  Field-level defaults below take precedence where present.
 */
export type AppSettings_Serialize = {
	/**
	 *  Internal settings schema marker for one-time migrations. Fresh installs
	 *  start at the current version; existing stores missing this key are
	 *  treated as version 0 and migrated forward.
	 */
	settings_schema_version: number,
	/**
	 *  Defaults to empty on partial stores; the load path merges in the
	 *  default bindings for any missing keys before the settings are used.
	 */
	bindings: { [key in string]: ShortcutBinding },
	/**
	 *  Replaces the pre-0.10 `push_to_talk` bool; stores missing this key are
	 *  migrated from it in `apply_settings_migrations`.
	 */
	shortcut_activation: ShortcutActivation,
	/**
	 *  Hold-or-toggle only: a press held at least this long is push-to-talk,
	 *  anything shorter is a tap that locks recording on.
	 */
	hold_threshold_ms: number,
	audio_feedback: boolean,
	audio_feedback_volume: number | null,
	sound_theme: SoundTheme,
	start_hidden: boolean,
	autostart_enabled: boolean,
	update_checks_enabled: boolean,
	show_whats_new_on_update: boolean,
	/**
	 *  The app version whose What's New the user has already seen. Fresh installs
	 *  default to the current version (nothing is "new" to them). Existing users
	 *  upgrading from before this key existed are blanked by the migration so they
	 *  see the current release's notes — see `apply_settings_migrations`.
	 */
	whats_new_last_seen_version: string,
	selected_model: string,
	onboarding_completed: boolean,
	always_on_microphone: boolean,
	selected_microphone: string | null,
	/**
	 *  Which input channel to use on the selected microphone device.
	 *  None means "average all channels" (original behavior).
	 */
	selected_channel: number | null,
	clamshell_microphone: string | null,
	selected_output_device: string | null,
	translate_to_english: boolean,
	selected_language: string,
	overlay_position: OverlayPosition_Serialize,
	debug_mode: boolean,
	log_level: LogLevel,
	custom_words: string[],
	model_unload_timeout: ModelUnloadTimeout,
	word_correction_threshold: number | null,
	history_limit: number,
	recording_retention_period: RecordingRetentionPeriod,
	save_raw_audio: boolean,
	paste_method: PasteMethod,
	clipboard_handling: ClipboardHandling,
	auto_submit: boolean,
	auto_submit_key: AutoSubmitKey,
	post_process_enabled: boolean,
	post_process_provider_id: string,
	post_process_providers: PostProcessProvider[],
	post_process_api_keys: SecretMap,
	post_process_models: { [key in string]: string },
	post_process_prompts: LLMPrompt[],
	post_process_selected_prompt_id: string | null,
	mute_while_recording: boolean,
	append_trailing_space: boolean,
	append_trailing_newline: boolean,
	app_language: string,
	theme: Theme,
	custom_accent_color: string | null,
	/**
	 *  Zoom of the settings window (0.7–1.6, 1.0 = native), for screens whose
	 *  OS scaling makes the UI too small or too large. Applied as CSS zoom.
	 */
	ui_scale: number | null,
	experimental_enabled: boolean,
	lazy_stream_close: boolean,
	keyboard_implementation: KeyboardImplementation,
	show_tray_icon: boolean,
	paste_delay_ms: number,
	paste_delay_after_ms: number,
	/**
	 *  Debug-gated ("beta") receipt-sequenced paste: restore the clipboard only
	 *  after the target app actually reads the transcript, instead of after a
	 *  fixed delay. See `paste_tx`. macOS and Windows only.
	 */
	reliable_paste: boolean,
	typing_tool: TypingTool,
	external_script_path: string | null,
	filler_word_removal_enabled: boolean,
	custom_filler_words: string[] | null,
	transcribe_accelerator: TranscribeAcceleratorSetting,
	/**
	 *  Stable transcribe.cpp device selector. This is derived from the backend's
	 *  `device_id` when available (or its name for backends such as Metal),
	 *  never from the process-local device registry index.
	 */
	transcribe_gpu_device: string | null,
	extra_recording_buffer_ms: number,
	vad_enabled: boolean,
	/**
	 *  RNNoise noise suppression on the microphone path, before the VAD and
	 *  the model (`audio_toolkit::audio::DenoiseChain`). Off by default: it
	 *  adds a little latency and can make some voices sound processed; the
	 *  live VAD test in Settings → Advanced shows its effect.
	 */
	denoise_enabled: boolean,
	/**
	 *  RNNoise wet/dry mix (0–1): 1 = the suppressor's output, 0 = the input
	 *  untouched.
	 */
	denoise_strength: number | null,
	/**
	 *  RNNoise's own speech probability below which the suppressor mutes
	 *  the frame (0–1); 0 turns the gate off.
	 */
	denoise_vad_threshold: number | null,
	/**
	 *  How long audio keeps passing after the last frame above that
	 *  threshold, in milliseconds.
	 */
	denoise_vad_grace_ms: number,
	/**  Speech-probability threshold of the Earshot detector (0.05–0.95). */
	vad_threshold_earshot: number | null,
	/**
	 *  Which recording overlay to show: None / Minimal / Live. Streaming mode is
	 *  not gated on this — that follows model capability. Migrated from the old
	 *  `overlay_position` (position `none` → style `None`).
	 */
	overlay_style: OverlayStyle,
	/**
	 *  Whether the live streaming overlay should reveal text character-by-character
	 *  in direct/typewriter mode instead of chunk-by-chunk / word-by-word.
	 */
	overlay_direct_mode: boolean,
	/**  Speed at which characters appear in direct streaming mode (characters per second). */
	overlay_direct_speed: number,
	/**  Speed at which characters are typed in direct streaming paste method (characters per second). */
	direct_streaming_speed: number,
	/**
	 *  Whether the overlay shows live speech statistics: a speech/silence
	 *  indicator, a timer that counts only while you are actually speaking, and
	 *  the running average words per minute. Applies to both the Minimal and
	 *  Live overlays; ignored when the overlay is off.
	 */
	overlay_speech_stats: boolean,
	/**
	 *  How long silence must last before the speech timer stops counting.
	 *  Shorter gaps are treated as part of the same utterance, so the timer does
	 *  not stall on the pauses between words.
	 */
	speech_pause_hold_ms: number,
	multi_stt_enabled: boolean,
	multi_stt_model_2: string | null,
	multi_stt_model_3: string | null,
	multi_stt_model_4: string | null,
	multi_stt_language_model_2: string | null,
	multi_stt_language_model_3: string | null,
	multi_stt_language_model_4: string | null,
	multi_stt_translate_model_2: boolean,
	multi_stt_translate_model_3: boolean,
	multi_stt_translate_model_4: boolean,
	multi_stt_keep_extra_models_loaded: boolean,
	multi_stt_merge_prompt: LLMPrompt | null,
	/**
	 *  Multi-STT Performance Mode: when enabled, simulate a keyboard shortcut
	 *  to boost CPU performance before transcription starts (FULL POWER) and
	 *  restore normal power after the merge/paste completes.
	 */
	multi_stt_performance_mode_enabled: boolean,
	multi_stt_performance_mode_trigger_on_start: boolean,
	multi_stt_performance_mode_full_power_shortcut: string,
	multi_stt_performance_mode_normal_shortcut: string,
	mic_idle_timeout_value: number,
	mic_idle_timeout_unit: MicIdleTimeoutUnit,
	mic_idle_infinite: boolean,
	native_streaming_latency_presets: { [key in string]: NativeStreamingLatencyPreset },
	/**  "Transcribe Files" page (fork feature). */
	file_transcription: FileTranscriptionSettings,
	/**  "Live Mode" page (fork feature). */
	live_mode: LiveModeSettings,
	/**  "Live FFT" page (fork feature). */
	live_fft: LiveFftSettings,
	/**
	 *  The recording overlay's picture of the microphone (which views, style,
	 *  waveform window, size); the analysis follows `live_fft`.
	 */
	overlay_scope: OverlayScopeSettings,
	/**  In-app llama.cpp server (fork feature). */
	llama: LlamaSettings,
};

/**  Metadata describing an architecture plugin module. */
export type ArchPluginInfo = {
	/**  Architecture identifier (e.g. "parakeet", "granite", "qwen3_asr", "whisper"). */
	name: string,
	/**  Absolute filesystem path to the plugin module. */
	path: string,
	/**  Whether Handy explicitly loaded this module (see `EXPLICITLY_LOADED`). */
	is_loaded: boolean,
	/**  File size in bytes. */
	file_size_bytes: number | null,
};

export type AudioDevice = {
	index: string,
	name: string,
	is_default: boolean,
};

export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter";

export type AvailableAccelerators = {
	transcribe: string[],
	gpu_devices: GpuDeviceOption[],
};

/**
 *  Result of benchmarking a single quantization variant — returned to the
 *  frontend so it can render per-quant timings next to each variant chip.
 */
export type BenchmarkResult = {
	quant: string,
	model_id: string,
	filename: string,
	size_mb: number,
	avg_time_ms: number | null,
	/**
	 *  Duration of the reference recording, so the frontend can render a
	 *  real-time factor (`audio_secs / (avg_time_ms / 1000)`) alongside the
	 *  raw timing.
	 */
	audio_secs: number | null,
	is_default: boolean,
};

export type BindingResponse = {
	success: boolean,
	binding: ShortcutBinding | null,
	error: string | null,
};

export type ClipboardHandling = "dont_modify" | "copy_to_clipboard";

/**
 *  A system CUDA toolkit whose runtime DLLs a CUDA build can load instead of
 *  the bundled `cudart` package.
 */
export type CudaToolkitInfo = {
	/**
	 *  Folder that holds `cudart64_*.dll` (CUDA 13 keeps it in `bin\x64`,
	 *  CUDA 12 and older in `bin`).
	 */
	runtime_dir: string,
	/**  Toolkit version as the installer names it (`13.3`), when known. */
	version: string | null,
	/**
	 *  Whether `runtime_dir` is on the PATH Handy was started with. When it is
	 *  not, `LlamaServerManager::start` prepends it to the child's PATH.
	 */
	on_path: boolean,
	/**
	 *  Whether cuBLAS (`cublas64_*` + `cublasLt64_*`) sits next to cudart —
	 *  llama.cpp's CUDA backend needs both.
	 */
	has_cublas: boolean,
};

export type CustomSounds = {
	start: boolean,
	stop: boolean,
};

export type DurationMetricSummary = {
	sample_count: number,
	minimum_ms: number | null,
	average_ms: number | null,
	maximum_ms: number | null,
};

export type FftBallisticsMode = 
/**  Per-frame smoothing coefficients (0 = follow instantly). */
"coefficient" | 
/**  Time constants in milliseconds, independent of the update rate. */
"milliseconds";

export type FftDbReference = 
/**  0 dB = the loudest bin of this frame. */
"frame_peak" | 
/**  0 dB = digital full scale. */
"dbfs" | 
/**  0 dB = a slow peak follower (1.5 s release). */
"agc";

export type FftLoudnessMode = 
/**  Linear magnitude. */
"off" | 
/**  Decibels relative to the reference. */
"db" | 
/**  Decibels mapped onto 0…1 over `db_range`. */
"db_normalized";

export type FftMagnitudeNorm = 
/**  `mean(window) == 1`; a full-scale sine peaks at `window / 2`. */
"coherent_gain" | 
/**  `sum(window) == 2`; a sine of amplitude 1 reads 1.0. */
"full_scale";

/**  Frequency axis of the spectrum. */
export type FftScale = "log" | "mel" | "erb" | "bark" | "chroma" | "linear" | 
/**  Mel + Log blend. */
"melog";

/**  Which signal the Live FFT page analyses. */
export type FftSource = 
/**
 *  The microphone at its native rate, before noise suppression — the
 *  full bandwidth the device delivers (24 kHz at 48 kHz).
 */
"microphone" | 
/**
 *  The 48 kHz frames as they leave RNNoise (full bandwidth), or the
 *  untouched microphone while suppression is off, so toggling it is a
 *  direct before/after.
 */
"denoised" | 
/**
 *  The 16 kHz frames a model hears: after resampling and noise
 *  suppression, before the VAD. Bandwidth stops at 8 kHz.
 */
"processed";

export type FftWarpInterp = 
/**  Two taps. */
"linear" | 
/**  Catmull-Rom, four taps: a 16K FFT with cubic looks like 32K with linear. */
"cubic";

export type FftWeighting = "off" | 
/**  IEC 61672 A-weighting. */
"a" | 
/**  C-weighting. */
"c" | 
/**  ITU-R 468 noise weighting. */
"itu468";

export type FftWindowLengthMode = "samples" | "milliseconds";

export type FftWindowType = "kaiser" | "hann" | "hamming" | "blackman" | "blackman_harris" | "rectangular";

export type FileJobStatus = "queued" | "decoding" | "transcribing" | "merging" | "post_processing" | "saving" | "done" | "failed" | "cancelled";

/**
 *  Progress of one file inside a job. The last event of a job carries
 *  `batch_finished = true` (with `index == total`) so the UI can leave its
 *  "running" state even if an individual event was missed.
 */
export type FileTranscriptionEvent = {
	job_id: number,
	/**  0-based position in the job (== `total` on the batch-finished event). */
	index: number,
	total: number,
	path: string,
	status: FileJobStatus,
	segment: number | null,
	segments: number | null,
	text: string | null,
	output_path: string | null,
	error: string | null,
	audio_seconds: number | null,
	elapsed_ms: number | null,
	batch_finished: boolean,
};

/**  How the "Transcribe Files" page turns one audio file into text. */
export type FileTranscriptionMode = 
/**  Primary model only, no LLM. */
"simple" | 
/**  Primary model, then the selected post-processing prompt. */
"post_process" | 
/**
 *  Primary + configured extra models, merged with the Multi-STT prompt
 *  (concatenated when no merge prompt / provider is configured).
 */
"multi_stt" | 
/**  Multi-STT merge, then the post-processing prompt on the merged text. */
"multi_stt_post_process";

/**
 *  Settings of the "Transcribe Files" page. Grouped into one struct so the
 *  page persists through a single command instead of one per field.
 */
export type FileTranscriptionSettings = {
	mode?: FileTranscriptionMode,
	/**
	 *  Folder the transcripts are written to. `None` writes each transcript
	 *  next to its source audio file.
	 */
	output_dir?: string | null,
	output_format?: TranscriptOutputFormat,
	/**  Replace an existing transcript instead of appending `-2`, `-3`, …. */
	overwrite_existing?: boolean,
	/**  When a folder is added, also queue audio files from its sub-folders. */
	include_subfolders?: boolean,
	/**
	 *  Long recordings are decoded in segments of at most this many minutes,
	 *  cut at the quietest point near the boundary, so one file never holds
	 *  the engine (or memory) for an hour at a time. 1–60.
	 */
	max_segment_minutes?: number,
};

export type FileTranscriptionStatus = {
	running: boolean,
	job_id: number,
	total: number,
	completed: number,
	current_path: string | null,
};

/**  A GGUF file found in a folder, for the model / draft / mmproj pickers. */
export type GgufFile = {
	path: string,
	name: string,
	size_mb: number,
	/**  `model`, `draft` (MTP / speculative) or `mmproj`, guessed from the name. */
	kind: string,
};

export type GpuDeviceOption = {
	id: string,
	name: string,
	total_vram_mb: number,
};

export type HistoryEntry = {
	id: number,
	file_name: string,
	timestamp: number | null,
	saved: boolean,
	title: string,
	transcription_text: string,
	post_processed_text: string | null,
	post_process_prompt: string | null,
	post_process_requested: boolean,
	model_id: string | null,
	engine: string | null,
	audio_duration_ms: number | null,
	speech_duration_ms: number | null,
	sample_rate_hz: number | null,
	word_count: number | null,
	transcription_latency_ms: number | null,
	post_processing_latency_ms: number | null,
	language: string | null,
	mode: string | null,
	extra_models: string[] | null,
};

export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number } | { action: "cleared" };

/**  Result of changing keyboard implementation */
export type ImplementationChangeResult = {
	success: boolean,
	/**  List of binding IDs that were reset to defaults due to incompatibility */
	reset_bindings: string[],
};

export type InstalledLlamaServer = {
	dir: string,
	name: string,
	backend: string,
	tag: string,
	has_server: boolean,
	size_mb: number,
	/**  Size of a bundled CUDA runtime (cudart/cuBLAS DLLs), 0 when none. */
	cuda_runtime_mb: number,
};

export type KeyboardDiagnosticReport = {
	secure_input_enabled: boolean,
	culprit_pid: number | null,
	culprit_name: string | null,
	/**  Counts only — key identity is deliberately never captured. */
	key_down: number,
	key_up: number,
	flags_changed: number,
	mouse: number,
	duration_ms: number,
};

export type KeyboardImplementation = "tauri" | "handy_keys";

export type LLMPrompt = {
	id: string,
	name: string,
	prompt: string,
};

export type LiveChunkInfo = {
	index: number,
	path: string | null,
	duration_ms: number | null,
	bytes: number | null,
	text_chars: number,
};

/**
 *  One analysed frame: `output_bins` values in the unit the loudness mode
 *  selects (linear magnitude, dB, or 0…1). Sent to the main window only,
 *  at `update_rate_hz`.
 */
export type LiveFftFrameEvent = {
	seq: number,
	bins: (number | null)[],
	peak_hz: number | null,
	peak_value: number | null,
	silent: boolean,
	dsp_us: number | null,
};

export type LiveFftPhase = "idle" | "starting" | "running" | "stopping" | "error";

/**
 *  Settings of the "Live FFT" page, grouped the way the page shows them
 *  (Spectrum, EQ, Window & Weighting, Loudness & Ballistics, Performance).
 *  `update_rate_hz` is the analysis frame rate; there is no planner policy
 *  or poll interval to configure, since rustfft plans are instant and the
 *  settings are pushed, not polled.
 */
export type LiveFftSettings = {
	source?: FftSource,
	scale?: FftScale,
	warp_interpolation?: FftWarpInterp,
	/**  Highest frequency on the axis; clamped to Nyquist at run time. */
	display_max_hz?: number | null,
	/**  Size of the warped spectrum handed to the page (32…8192). */
	output_bins?: number,
	/**  0 = linear grid, 1 = fully perceptual. */
	warp_blend?: number | null,
	/**  Lowest frequency of the Log / Melog grid. */
	log_floor_hz?: number | null,
	window_length_mode?: FftWindowLengthMode,
	/**  Analysis window in samples (3175 = 72 ms at 44.1 kHz). */
	window_samples?: number,
	/**  Analysis window in milliseconds, used when the mode says so. */
	window_ms?: number | null,
	/**
	 *  Zero-padded transform length; grown to the next power of two above
	 *  the window when that is larger.
	 */
	fft_size?: number,
	eq_enabled?: boolean,
	high_shelf?: boolean,
	low_shelf?: boolean,
	high_gain_db?: number | null,
	high_cutoff_hz?: number | null,
	low_gain_db?: number | null,
	low_cutoff_hz?: number | null,
	eq_q?: number | null,
	/**  Wet/dry blend of the EQ (0…5). */
	eq_amount?: number | null,
	window_type?: FftWindowType,
	kaiser_beta?: number | null,
	weighting?: FftWeighting,
	magnitude_norm?: FftMagnitudeNorm,
	loudness_mode?: FftLoudnessMode,
	db_reference?: FftDbReference,
	/**  Floor of the dB display, in dB below the reference. */
	db_range?: number | null,
	ballistics_enabled?: boolean,
	ballistics_mode?: FftBallisticsMode,
	/**  Per-frame attack coefficient (0…0.99). */
	attack?: number | null,
	/**  Per-frame release coefficient (0…0.99). */
	release?: number | null,
	attack_ms?: number | null,
	release_ms?: number | null,
	/**
	 *  Run the transform on the analysis worker thread (on) or inline on the
	 *  audio consumer thread (off).
	 */
	async_analysis?: boolean,
	/**  Spectrum frames per second sent to the page (5…60). */
	update_rate_hz?: number,
	/**
	 *  Run the speech detector on the analysed session and report its
	 *  per-frame verdicts to the page (`VadTestEvent`), so the threshold and
	 *  noise suppression can be tuned against the spectrum. Changing it
	 *  restarts a running session (the VAD policy is fixed per recording).
	 */
	show_vad?: boolean,
};

/**  Emitted on every phase change and roughly once a second while running. */
export type LiveFftStateEvent = {
	status: LiveFftStatus,
};

/**  Status snapshot — the telemetry rows the page shows. */
export type LiveFftStatus = {
	phase: LiveFftPhase,
	error: string | null,
	stop_reason: LiveFftStopReason | null,
	/**  Rate of the analysed signal (native microphone rate or 16 kHz). */
	sample_rate: number,
	fft_size: number,
	window_samples: number,
	linear_bins: number,
	/**  Magnitude bins actually computed. */
	magnitude_bins: number,
	output_bins: number,
	identity_warp: boolean,
	/**  Magnitude of a full-scale sine under the current normalisation. */
	full_scale_ref: number | null,
	/**  Highest frequency on the axis after the Nyquist clamp. */
	display_max_hz: number | null,
	nyquist_hz: number | null,
	update_rate_hz: number,
	async_analysis: boolean,
	/**  Frames analysed this session. */
	frames: number,
	/**  Samples the ring could not take (the worker fell behind). */
	dropped_samples: number,
	dsp_us_last: number | null,
	dsp_us_avg: number | null,
	dsp_us_max: number | null,
	started_at_ms: number | null,
	/**  Frequency of every output bin (rebuilt with the warp tables). */
	axis_hz: (number | null)[],
};

/**  Why the last session ended on its own. */
export type LiveFftStopReason = 
/**  The recording was ended elsewhere (cancel hotkey, tray). */
"cancelled" | 
/**  The main window stayed hidden for [`HIDDEN_AUTO_STOP`]. */
"window_hidden";

export type LiveModePhase = "idle" | "starting" | "listening" | "rotating" | "stopping" | "error";

/**  Settings of the "Live Mode" page (continuous recording + live transcript). */
export type LiveModeSettings = {
	/**
	 *  Session folders are created under this directory. `None` uses
	 *  `<app data>/live_mode`.
	 */
	output_dir?: string | null,
	/**  Target length of one audio chunk / transcript segment in minutes. 1–60. */
	chunk_minutes?: number,
	transcript_format?: TranscriptOutputFormat,
	granularity?: LiveTranscriptGranularity,
	/**  Write the raw microphone signal to `chunk_NNNN.wav` files. */
	save_audio?: boolean,
	/**
	 *  Rotate chunks on the first pause once 80 % of `chunk_minutes` has
	 *  elapsed, so a cut never lands mid-word.
	 */
	prefer_silence_boundary?: boolean,
};

/**
 *  Emitted whenever the session status changes and roughly once a second
 *  while listening.
 */
export type LiveModeStateEvent = {
	status: LiveModeStatus,
};

export type LiveModeStatus = {
	phase: LiveModePhase,
	session_dir: string | null,
	transcript_path: string | null,
	model_id: string | null,
	/**  Number of the chunk currently being recorded (1-based). */
	chunk_index: number,
	chunks: LiveChunkInfo[],
	started_at_ms: number | null,
	elapsed_ms: number | null,
	current_chunk_ms: number | null,
	/**  Speech measured by the VAD in the current chunk. */
	current_chunk_speech_ms: number | null,
	/**  Bytes of committed transcript text. */
	transcript_bytes: number | null,
	error: string | null,
};

/**
 *  Incremental transcript update. `reset` replaces the UI's committed text
 *  with `stable_appended`; otherwise `stable_appended` is appended to it.
 *  `live` always replaces the volatile tail.
 */
export type LiveModeTranscriptEvent = {
	reset: boolean,
	stable_appended: string,
	live: string,
};

/**  A past (or current) session folder, for the page's session list. */
export type LiveSessionInfo = {
	dir: string,
	name: string,
	transcript_path: string | null,
	transcript_bytes: number | null,
	chunk_count: number,
	modified_ms: number | null,
};

/**  How Live Mode grows the transcript file while you speak. */
export type LiveTranscriptGranularity = 
/**  Mirror the live stream exactly, including the model's tentative tail. */
"character" | 
/**  Only write text up to the last completed word. */
"word";

/**  An existing llama.cpp install found outside Handy's data dir. */
export type LlamaDetectedInstall = {
	server_dir: string,
	model_path: string | null,
	draft_model_path: string | null,
	mmproj_path: string | null,
};

/**  Progress of one install, from download start to done/error. */
export type LlamaDownloadEvent = {
	tag: string,
	backend: string,
	/**  `downloading`, `extracting`, `done`, `error` */
	phase: string,
	downloaded_bytes: number | null,
	total_bytes: number | null,
	message: string | null,
	/**  Install folder, once `done`. */
	dir: string | null,
};

export type LlamaRelease = {
	tag: string,
	name: string,
	published_at: string,
	prerelease: boolean,
	/**  `b<number>` of this release or of the nightly it points to. */
	build_number: number,
	/**  Windows x64 binary assets (no cudart packages). */
	assets: LlamaReleaseAsset[],
	/**  For SemVer releases without binaries: the nightly tag that has them. */
	backing_tag: string | null,
};

export type LlamaReleaseAsset = {
	name: string,
	size_bytes: number | null,
	url: string,
	/**  `cuda-13.3`, `cuda-12.4`, `vulkan`, `cpu`, … parsed from the name. */
	backend: string,
};

/**  Snapshot of the supervised server. Also the payload of the state event. */
export type LlamaServerStateEvent = {
	status: LlamaStatus,
	/**  Human-readable reason for `Error`, or the last log line while starting. */
	message: string | null,
	pid: number | null,
	port: number,
	alias: string,
	/**  File name of the loaded model. */
	model: string | null,
	draft: boolean,
	mmproj: boolean,
	/**  Unix milliseconds when the server became ready. */
	ready_since_ms: number | null,
	/**  Backend guessed from the server folder name (cuda / vulkan / cpu). */
	backend: string | null,
};

/**
 *  The in-app llama.cpp server ("brain") behind post-processing and the
 *  Multi-STT merge. Defaults reproduce `launch_server_E2B_Q4.ps1`: Gemma 4
 *  E2B Q4 with its MTP draft, 8k context, sampling tuned for the merge/clean
 *  prompts (temp 0.05, top-p 0.35), reasoning off, alias
 *  `gemma-4-E2B-Q4-MTP`. See `llama_server::build_args`.
 */
export type LlamaSettings = {
	/**
	 *  Folder that contains `llama-server(.exe)`: an install made by Handy
	 *  (`<app data>/llama_cpp/<backend>-<tag>`) or any existing one.
	 */
	server_dir?: string | null,
	model_path?: string | null,
	/**  MTP / speculative draft model (`--model-draft`, `--spec-type draft-mtp`). */
	draft_model_path?: string | null,
	mmproj_path?: string | null,
	/**  Load the mmproj (vision/audio). Off saves ~1 GB of VRAM for text use. */
	mmproj_enabled?: boolean,
	port?: number,
	context_size?: number,
	/**  `-ngl`; -1 = all layers on the GPU. */
	gpu_layers?: number,
	/**  `--threads`; -1 = let llama.cpp choose. */
	threads?: number,
	flash_attn?: boolean,
	/**  `--reasoning on|off` (Gemma 4 thinking mode; off is much faster). */
	reasoning?: boolean,
	temperature?: number | null,
	top_p?: number | null,
	top_k?: number,
	min_p?: number | null,
	spec_draft_n_max?: number,
	/**  `--alias`; also the model name the post-processing provider sends. */
	alias?: string,
	/**  Appended verbatim to the generated arguments. */
	extra_args?: string,
	/**
	 *  When set, replaces the generated arguments entirely (everything after
	 *  the executable).
	 */
	custom_args?: string | null,
	/**
	 *  `LLAMA_ATTN_ROT_DISABLE=1` in the server environment (+3–4 % on short
	 *  prompts in the S2B2S benchmarks).
	 */
	attn_rot_disable?: boolean,
	/**  Start the server when Handy starts. */
	autostart?: boolean,
	/**  Start the server when a request targets it and it is not running. */
	start_on_demand?: boolean,
	stop_on_exit?: boolean,
	/**  Preferred release asset: `auto`, `cuda-13.3`, `cuda-12.4`, `vulkan`, `cpu`. */
	backend?: string,
	/**  `latest`, `stable` or `nightly` for the release list. */
	channel?: string,
	/**
	 *  Also download the ~500 MB CUDA runtime package (cudart / cuBLAS) with
	 *  a CUDA build. Off, like the download script without `-IncludeCudart`:
	 *  a machine with the CUDA toolkit installed already has those DLLs.
	 */
	include_cudart?: boolean,
};

export type LlamaStatus = "stopped" | "starting" | "ready" | "error";

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

export type MicIdleTimeoutUnit = "seconds" | "minutes";

export type ModelInfo = {
	id: string,
	name: string,
	description: string,
	filename: string,
	source: ModelSource,
	size_mb: number,
	is_downloaded: boolean,
	is_downloading: boolean,
	partial_size: number | null,
	accuracy_score: number | null,
	speed_score: number | null,
	supports_translation: boolean,
	is_recommended: boolean,
	supported_languages: string[],
	supports_language_selection: boolean,
	is_custom: boolean,
	supports_streaming: boolean,
	supports_language_detection: boolean,
	/**
	 *  Which native streaming latency extension the model supports (if any).
	 *  Populated for catalog streaming models; `None` for legacy/custom.
	 */
	native_streaming_latency_kind?: NativeStreamingLatencyKind | null,
};

export type ModelLoadStatus = {
	is_loaded: boolean,
	current_model: string | null,
};

/**
 *  Where a model comes from and how Handy obtains it — the routing discriminant
 *  for downloading and on-disk resolution.
 */
export type ModelSource = 
/**  Direct HTTP download from a URL (current blob.handy.computer hosting). */
({ Url: {
	url: string,
	/**  Expected SHA-256 for integrity verification; `None` skips it. */
	sha256: string | null,
} }) & { HuggingFace?: never } | 
/**
 *  A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 *  HF cache (so other tools reuse it). The file within the repo is
 *  [`ModelInfo::filename`].
 */
({ HuggingFace: {
	repo_id: string,
	revision: string,
} }) & { Url?: never } | 
/**
 *  Already present on disk — a user-provided custom model, or one discovered
 *  in a shared cache. Nothing to download.
 */
"Local";

export type ModelUnloadTimeout = "never" | "immediately" | "min2" | "min5" | "min10" | "min15" | "hour1" | "sec15";

/**
 *  Which transcribe-cpp stream extension a catalog streaming model exposes for
 *  low-latency tuning. `None` means the model has no configurable latency
 *  extension (non-streaming models).
 */
export type NativeStreamingLatencyKind = "parakeet_buffered" | "nemotron_3_5_cache_aware" | "nemotron_speech_cache_aware";

/**
 *  User-facing latency preset for native streaming models (Parakeet Buffered,
 *  Nemotron cache-aware). Stored per-model-id in
 *  [`AppSettings::native_streaming_latency_presets`]. `Accurate` is the default
 *  (runtime default — no stream extension attached), so it is the unit value.
 */
export type NativeStreamingLatencyPreset = "fastest" | "fast" | "balanced" | "accurate";

export type OverlayPosition = OverlayPosition_Serialize | OverlayPosition_Deserialize;

export type OverlayPosition_Deserialize = "top" | "bottom" | "none";

export type OverlayPosition_Serialize = "top" | "bottom";

/**
 *  The picture the recording overlay draws of the microphone (see
 *  `live_fft::scope` and `overlay/OverlayScope.tsx`). The analysis behind it
 *  follows `live_fft`; this only shapes the display. Mirrored by
 *  `src/lib/overlayScope.ts`.
 */
export type OverlayScopeSettings = {
	/**  Draw the spectrum view. */
	show_spectrum?: boolean,
	/**  Draw the waveform view. */
	show_wave?: boolean,
	spectrum_style?: OverlayScopeStyle,
	/**
	 *  Draw the spectrum rising from the centre line with its negative
	 *  mirrored below, so it reads like the centred waveform beside it.
	 */
	spectrum_mirror?: boolean,
	/**
	 *  Keep a slowly falling marker at each column's recent peak, like the
	 *  Live FFT page's peak hold.
	 */
	peak_hold?: boolean,
	/**  Samples of raw audio the waveform view covers (256…16384). */
	wave_samples?: number,
	/**
	 *  Raised-cosine fade at each end of that window, in samples
	 *  (0…half the window), so the trace starts and ends at zero.
	 */
	wave_taper_samples?: number,
	/**
	 *  Auto-gain floor of the waveform as a full-scale fraction: quieter
	 *  signals are not blown up to full height (0.001…0.5).
	 */
	wave_gain_floor?: number | null,
	/**  Width of each view in logical pixels (32…160). */
	view_width?: number,
	/**  Height of the views in logical pixels (14…48). */
	view_height?: number,
};

/**  How the recording overlay's spectrum is drawn. */
export type OverlayScopeStyle = "area" | "line" | "bars";

/**
 *  Which recording overlay to display. `Minimal` and `Live` share one base
 *  (the pill); `Live` grows into the panel that shows live transcription text.
 *  `None` hides the overlay entirely. Decoupled from whether the model runs in
 *  streaming mode (that is driven purely by model capability).
 */
export type OverlayStyle = "none" | "minimal" | "live";

export type PaginatedHistory = {
	entries: HistoryEntry[],
	has_more: boolean,
};

export type PasteMethod = "ctrl_v" | "direct" | "direct_streaming" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script";

export type PermissionAccess = "allowed" | "denied" | "unknown";

export type PostProcessProvider = {
	id: string,
	label: string,
	base_url: string,
	allow_base_url_edit?: boolean,
	models_endpoint?: string | null,
	supports_structured_output?: boolean,
};

/**
 *  A single quantization variant of a catalog model — returned to the frontend
 *  so the UI can render a quant picker (chips / dropdown) and let the user
 *  select or download a non-default quant.
 */
export type QuantVariant = {
	quant: string,
	filename: string,
	model_id: string,
	size_mb: number,
	is_default: boolean,
};

export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days3" | "weeks2" | "months3";

export type SecretMap = { [key in string]: string };

export type SecureInputStatus = {
	/**  Secure input is currently enabled (live check) */
	enabled: boolean,
	/**
	 *  Enabled continuously long enough to be considered stuck (not just a
	 *  password field gaining momentary focus)
	 */
	sustained: boolean,
	culprit_pid: number | null,
	culprit_name: string | null,
	/**  Carbon fallback registrations are currently active */
	fallback_active: boolean,
	/**  Binding ids shadow-registered with identical semantics */
	covered_bindings: string[],
	/**  Side-specific binding ids widened to match either side while shadowed */
	degraded_bindings: string[],
	/**  Binding ids that cannot fire at all (e.g. fn+key, registration failure) */
	uncovered_bindings: string[],
	/**
	 *  The user tried to record a shortcut while secure input was active.
	 *  Treated as user impact even when every binding is covered, so the
	 *  warning banner appears and explains why recording refused.
	 */
	recorder_blocked: boolean,
};

/**  How the transcribe shortcut's key events drive a recording. */
export type ShortcutActivation = 
/**  Press to start, press again to stop. */
"toggle" | 
/**  Hold to record, release to stop. */
"push_to_talk" | 
/**
 *  Hold to record and release to stop, or tap to keep recording until the
 *  next press. Which one it was is decided by how long the key was held
 *  (`hold_threshold_ms`).
 */
"hold_or_toggle";

export type ShortcutBinding = {
	id: string,
	name: string,
	description: string,
	default_binding: string,
	current_binding: string,
};

export type SoundTheme = "marimba" | "pop" | "custom";

/**
 *  Live speech statistics for the recording overlay.
 * 
 *  Not a fixed-rate stream: the recorder sends it
 *  when the speaking/silent state flips, and roughly every 150 ms while speech
 *  continues. A silent stretch produces no events at all.
 */
export type SpeechActivityEvent = {
	/**
	 *  Whether the user is speaking right now, debounced by the configured
	 *  pause tolerance so it does not flicker between words.
	 */
	speaking: boolean,
	/**
	 *  Milliseconds of speech so far in this recording, excluding pauses long
	 *  enough to count as silence. The overlay divides its word count by this
	 *  to get words per minute.
	 */
	speech_ms: number,
};

export type StatisticsRange = {
	start_ms: number | null,
	end_ms: number | null,
};

export type StatisticsSummary = {
	range: StatisticsRange,
	transcription_count: number,
	total_words: number,
	average_words: number | null,
	total_audio_duration_ms: number | null,
	average_audio_duration_ms: number | null,
	approximate_words_per_minute: number | null,
	current_streak_days: number,
	transcription_latency: DurationMetricSummary,
	post_processing_latency: DurationMetricSummary,
};

export type StatisticsUpdatedEvent = null;

/**  Phase of the streaming overlay card, emitted to drive its UI state. */
export type StreamPhase = 
/**
 *  Receiving audio / live text (or waiting for the stream to begin). Rust
 *  does not emit this today; the frontend starts in this phase and Rust only
 *  emits transitions away from it.
 */
"listening" | 
/**  Finalizing or post-processing — show a spinner. */
"working";

/**  Emitted to switch the streaming overlay to a working spinner. */
export type StreamPhaseEvent = StreamPhaseEvent_Serialize | StreamPhaseEvent_Deserialize;

/**  Emitted to switch the streaming overlay to a working spinner. */
export type StreamPhaseEvent_Deserialize = {
	phase: StreamPhase,
	/**  Present only when `phase` is `Working`. */
	kind: StreamWorkKind | null,
};

/**  Emitted to switch the streaming overlay to a working spinner. */
export type StreamPhaseEvent_Serialize = {
	phase: StreamPhase,
	/**  Present only when `phase` is `Working`. */
	kind?: StreamWorkKind | null,
};

/**
 *  Live transcription snapshot emitted to the overlay during a streaming run.
 *  `committed` is the append-only, flicker-free prefix; `tentative` is the
 *  volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = {
	committed: string,
	tentative: string,
};

/**  Semantic kind of "working" phase, used to localize the spinner label. */
export type StreamWorkKind = "transcribing" | "polishing";

export type SystemStatsEvent = {
	cpu_percent: number | null,
	mem_used_mb: number,
	mem_total_mb: number,
	gpu_name: string | null,
	gpu_percent: number | null,
	vram_used_mb: number | null,
	vram_total_mb: number | null,
	gpu_temp_c: number | null,
};

/**
 *  UI appearance mode. `System` follows the OS `prefers-color-scheme`; `Light`
 *  and `Dark` force one of the two palettes Handy already ships.
 */
export type Theme = "system" | "light" | "dark";

export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu";

/**  Text file flavour written by the file-transcription and Live Mode pages. */
export type TranscriptOutputFormat = "txt" | "md";

export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool";

/**
 *  One update of the live VAD test: what the detector thought of the latest
 *  microphone frame. Emitted only while the Advanced page's test or the Live
 *  FFT page's voice-detection view runs, never during normal dictation.
 */
export type VadTestEvent = {
	/**  Raw 0–1 speech score before hysteresis (`None` with VAD disabled). */
	score: number | null,
	/**  Verdict after hysteresis — the threshold the slider sets. */
	voiced: boolean,
	/**
	 *  Whether the frame reached the recording after smoothing (prefill /
	 *  hangover), i.e. what a model would have heard.
	 */
	kept: boolean,
	/**  Peak input level of the frame, 0–1. */
	level: number | null,
	/**
	 *  RNNoise's own speech probability of the latest 10 ms frame while
	 *  suppression is on; its gate threshold compares against it.
	 */
	denoise_prob: number | null,
};

export type WindowsMicrophonePermissionStatus = {
	supported: boolean,
	overall_access: PermissionAccess,
	device_access: PermissionAccess,
	app_access: PermissionAccess,
	desktop_app_access: PermissionAccess,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

